Eric Sunshine made the following changes:
-*- Updated Swig test in configure.ac to utilize new optional version
    number component capability of progver.m4.  This is needed because
    older versions of Swig emit a 2-part version number (such as 1.1),
    whereas newer ones emit a 3-part number (such as 1.3.19).

-*- Fixed problem where recent change to configure.ac caused it to create
    several files deep within the CS source tree.  This is a problem
    because the CS source tree might be on a read-only volume (such as a
    CD-ROM), or might be shared (perhaps via NFS) between several builds.
    Furthermore, it failed when the build directory differed from the
    source directory.  Instead of creating the one-line csperlxs.c file in
    the plugins/cscript/csperl5 directory to include the appropriate .inc
    file, it now emits the header property CS_PERL5_XSINC to volatile.h
    with the value of the .inc file to include.

-*- Fixed problem where configure.ac was creating the file csperlxs.inc
    during the configuration phase.  It is not the responsibility of the
    configure script to create output files.  Instead, it is the
    responsibility of config.status to see to this chore.  Therefore,
    configure.ac now invokes AC_CONFIG_COMMANDS() to delegate creation of
    csperlxs.inc to config.status.

-*- Fixed bug where recent changes to configure.ac caused it to reference
    the non-existent shell variable PERL5.EXTUTILS.DYNALOADER, thus
    causing creation of csperlxs.inc to fail.

-*- The configure script no longer emits the PERL5.EXTUTILS.AVAILABLE and
    PERL5.EXTUTILS.DYNALOADER build properties to config.mak and Jamconfig
    since recent changes obsoleted these variables, and they are no longer
    used by the csperl5 makefile and Jamfile.

-*- Fixed a number of errors in csperl5.mak where it was not respecting
    $(SRCDIR), thus resulting in build failure when building outside of
    the CS source tree.

-*- Fixed bugs in csperl5.mak where it used CEX.CSPERL5 and CIN.CSPERL5 in
    some places but CEX.PERL5 and CIN.PERL5 in others.


git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/trunk@13876 8cc4aa7f-3514-0410-904f-f2cc9021211c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2771,12 +2771,31 @@ echo $ECHO_N "checking if bison version >= 1.35... $ECHO_C" >&6
 if test "${cs_cv_prog_bison_version_ok+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  cs_prog_bison_is_version=`$BISONBIN -V | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
-cs_prog_bison_min_version=`echo 1.35 | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
-cs_prog_bison_is_ver_1=`echo $cs_prog_bison_is_version | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1/'`
-cs_prog_bison_is_ver_2=`echo $cs_prog_bison_is_version | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\2/'`
-cs_prog_bison_min_ver_1=`echo $cs_prog_bison_min_version | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1/'`
-cs_prog_bison_min_ver_2=`echo $cs_prog_bison_min_version | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\2/'`
+
+cs_prog_bison_is_version=
+cs_prog_bison_min_version=
+cs_prog_bison_is_suffix=
+cs_prog_bison_min_suffix=
+cs_prog_bison_is_suffix_done=
+cs_prog_bison_min_suffix_done=
+
+
+
+test -z $cs_prog_bison_is_version && cs_prog_bison_is_version=`$BISONBIN -V | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
+test -n "$cs_prog_bison_is_version" && test -z $cs_prog_bison_is_suffix_done  && { cs_prog_bison_is_suffix_done=yes ; cs_prog_bison_is_suffix= ; }
+
+
+
+
+
+test -z $cs_prog_bison_min_version && cs_prog_bison_min_version=`echo 1.35 | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
+test -n "$cs_prog_bison_min_version" && test -z $cs_prog_bison_min_suffix_done  && { cs_prog_bison_min_suffix_done=yes ; cs_prog_bison_min_suffix= ; }
+
+
+cs_prog_bison_is_ver_1=`echo ${cs_prog_bison_is_version}${cs_prog_bison_is_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1/'`
+cs_prog_bison_is_ver_2=`echo ${cs_prog_bison_is_version}${cs_prog_bison_is_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\2/'`
+cs_prog_bison_min_ver_1=`echo $cs_prog_bison_min_version${cs_prog_bison_min_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1/'`
+cs_prog_bison_min_ver_2=`echo $cs_prog_bison_min_version${cs_prog_bison_min_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\2/'`
 cs_cv_prog_bison_version_ok=''
 test -z "$cs_cv_prog_bison_version_ok" && { expr "$cs_prog_bison_is_ver_1" ">=" "$cs_prog_bison_min_ver_1" >/dev/null || cs_cv_prog_bison_version_ok=no ; }
 test -z "$cs_cv_prog_bison_version_ok" && { expr "$cs_prog_bison_min_ver_1" ">=" "$cs_prog_bison_is_ver_1" >/dev/null || cs_cv_prog_bison_version_ok=yes ; }
@@ -3229,14 +3248,41 @@ echo $ECHO_N "checking if swig version >= 1.3.14... $ECHO_C" >&6
 if test "${cs_cv_prog_swig_version_ok+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  cs_prog_swig_is_version=`$SWIGBIN -version 2>&1 | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
-cs_prog_swig_min_version=`echo 1.3.14 | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
-cs_prog_swig_is_ver_1=`echo $cs_prog_swig_is_version | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1/'`
-cs_prog_swig_is_ver_2=`echo $cs_prog_swig_is_version | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\2/'`
-cs_prog_swig_is_ver_3=`echo $cs_prog_swig_is_version | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\3/'`
-cs_prog_swig_min_ver_1=`echo $cs_prog_swig_min_version | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1/'`
-cs_prog_swig_min_ver_2=`echo $cs_prog_swig_min_version | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\2/'`
-cs_prog_swig_min_ver_3=`echo $cs_prog_swig_min_version | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\3/'`
+
+cs_prog_swig_is_version=
+cs_prog_swig_min_version=
+cs_prog_swig_is_suffix=
+cs_prog_swig_min_suffix=
+cs_prog_swig_is_suffix_done=
+cs_prog_swig_min_suffix_done=
+
+
+
+
+test -z $cs_prog_swig_is_version && cs_prog_swig_is_version=`$SWIGBIN -version 2>&1 | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
+test -n "$cs_prog_swig_is_version" && test -z $cs_prog_swig_is_suffix_done  && { cs_prog_swig_is_suffix_done=yes ; cs_prog_swig_is_suffix= ; }
+
+test -z $cs_prog_swig_is_version && cs_prog_swig_is_version=`$SWIGBIN -version 2>&1 | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
+test -n "$cs_prog_swig_is_version" && test -z $cs_prog_swig_is_suffix_done  && { cs_prog_swig_is_suffix_done=yes ; cs_prog_swig_is_suffix=.0 ; }
+
+
+
+
+
+
+test -z $cs_prog_swig_min_version && cs_prog_swig_min_version=`echo 1.3.14 | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
+test -n "$cs_prog_swig_min_version" && test -z $cs_prog_swig_min_suffix_done  && { cs_prog_swig_min_suffix_done=yes ; cs_prog_swig_min_suffix= ; }
+
+test -z $cs_prog_swig_min_version && cs_prog_swig_min_version=`echo 1.3.14 | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
+test -n "$cs_prog_swig_min_version" && test -z $cs_prog_swig_min_suffix_done  && { cs_prog_swig_min_suffix_done=yes ; cs_prog_swig_min_suffix=.0 ; }
+
+
+cs_prog_swig_is_ver_1=`echo ${cs_prog_swig_is_version}${cs_prog_swig_is_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1/'`
+cs_prog_swig_is_ver_2=`echo ${cs_prog_swig_is_version}${cs_prog_swig_is_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\2/'`
+cs_prog_swig_is_ver_3=`echo ${cs_prog_swig_is_version}${cs_prog_swig_is_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\3/'`
+cs_prog_swig_min_ver_1=`echo $cs_prog_swig_min_version${cs_prog_swig_min_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1/'`
+cs_prog_swig_min_ver_2=`echo $cs_prog_swig_min_version${cs_prog_swig_min_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\2/'`
+cs_prog_swig_min_ver_3=`echo $cs_prog_swig_min_version${cs_prog_swig_min_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\3/'`
 cs_cv_prog_swig_version_ok=''
 test -z "$cs_cv_prog_swig_version_ok" && { expr "$cs_prog_swig_is_ver_1" ">=" "$cs_prog_swig_min_ver_1" >/dev/null || cs_cv_prog_swig_version_ok=no ; }
 test -z "$cs_cv_prog_swig_version_ok" && { expr "$cs_prog_swig_min_ver_1" ">=" "$cs_prog_swig_is_ver_1" >/dev/null || cs_cv_prog_swig_version_ok=yes ; }
@@ -3672,12 +3718,7 @@ fi
 echo "$as_me:$LINENO: result: $cs_cv_perl_mod_embed" >&5
 echo "${ECHO_T}$cs_cv_perl_mod_embed" >&6
     if test $cs_cv_perl_mod_embed = yes; then
-  cs_makefile_text="${cs_makefile_text}PERL5.EXTUTILS.AVAILABLE = yes
-"
-    cs_jamconfig_text="${cs_jamconfig_text}PERL5.EXTUTILS.AVAILABLE ?= \"yes\" ;
-"
-
-	echo "$as_me:$LINENO: checking for perl DynaLoader module" >&5
+  echo "$as_me:$LINENO: checking for perl DynaLoader module" >&5
 echo $ECHO_N "checking for perl DynaLoader module... $ECHO_C" >&6
 if test "${cs_cv_perl_mod_dynaloader+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3696,27 +3737,12 @@ fi
 echo "$as_me:$LINENO: result: $cs_cv_perl_mod_dynaloader" >&5
 echo "${ECHO_T}$cs_cv_perl_mod_dynaloader" >&6
 	if test $cs_cv_perl_mod_dynaloader = yes; then
-  cs_makefile_text="${cs_makefile_text}PERL5.EXTUTILS.DYNALOADER = DynaLoader
-"
-    cs_jamconfig_text="${cs_jamconfig_text}PERL5.EXTUTILS.DYNALOADER ?= \"DynaLoader\" ;
+            ac_config_commands="$ac_config_commands include/csperlxs.inc"
+
+	    cs_header_text="${cs_header_text}#define CS_PERL5_XSINC \"csperlxs.inc\"
 "
 fi
 
-
-	{ (echo "$as_me:$LINENO: \$PERL -MExtUtils::Embed -e xsinit -- -o \\
-	  include/cssys/csperlxs.inc -std \${PERL5.EXTUTILS.DYNALOADER} cspace") >&5
-  ($PERL -MExtUtils::Embed -e xsinit -- -o \
-	  include/cssys/csperlxs.inc -std ${PERL5.EXTUTILS.DYNALOADER} cspace) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }
-	{ (echo "$as_me:$LINENO: echo '#include \"cssys/csperlxs.inc\"' \\
-	  > plugins/cscript/csperl5/csperlxs.c") >&5
-  (echo '#include "cssys/csperlxs.inc"' \
-	  > plugins/cscript/csperl5/csperlxs.c) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }
 	cs_cv_perl_cflags=`{ (echo "$as_me:$LINENO: \$PERL -MExtUtils::Embed -e ccopts") >&5
   ($PERL -MExtUtils::Embed -e ccopts) 2>&5
   ac_status=$?
@@ -3733,13 +3759,8 @@ else
 echo "$as_me: Recommend you install the latest release of Perl 5." >&6;}
 	{ echo "$as_me:$LINENO: http://www.perl.org/" >&5
 echo "$as_me: http://www.perl.org/" >&6;}
-	{ (echo "$as_me:$LINENO: echo '#include \"cssys/csperlxs_fallback.inc\"' \\
-	  > plugins/cscript/csperl5/csperlxs.c") >&5
-  (echo '#include "cssys/csperlxs_fallback.inc"' \
-	  > plugins/cscript/csperl5/csperlxs.c) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }
+	cs_header_text="${cs_header_text}#define CS_PERL5_XSINC \"cssys/csperlxs_fallback.inc\"
+"
 
 	echo "$as_me:$LINENO: checking for perl Config module" >&5
 echo $ECHO_N "checking for perl Config module... $ECHO_C" >&6
@@ -3948,12 +3969,12 @@ else
   (exit $ac_status); }`
 	    cs_cv_python_base_libs=`{ (echo "$as_me:$LINENO: \$PYTHON -c \\
 		'import distutils.sysconfig ; \\
-		print (distutils.sysconfig.get_config_var(\"LIBS\") or \"\") + \" \" + \\
-		(distutils.sysconfig.get_config_var(\"SYSLIBS\") or \"\")'") >&5
+		print (distutils.sysconfig.get_config_var(\"LIBS\") or \"\") + \\
+		\" \" + (distutils.sysconfig.get_config_var(\"SYSLIBS\") or \"\")'") >&5
   ($PYTHON -c \
 		'import distutils.sysconfig ; \
-		print (distutils.sysconfig.get_config_var("LIBS") or "") + " " + \
-		(distutils.sysconfig.get_config_var("SYSLIBS") or "")') 2>&5
+		print (distutils.sysconfig.get_config_var("LIBS") or "") + \
+		" " + (distutils.sysconfig.get_config_var("SYSLIBS") or "")') 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }`
@@ -4428,16 +4449,15 @@ else
 fi
 
 
-#------------------------------------------------------------------------------
-# Use the CXXFLAGS and CFLAGS passed to configure
-#------------------------------------------------------------------------------
 
-# autoconf has some stupid defaults :-( so we need to filter all -O and -g
-# flags here
-CFLAGS=`echo "$CFLAGS" | sed 's/\-O.//g;s/\-g.//g'`
-CXXFLAGS=`echo "$CXXFLAGS" | sed 's/\-O.//g;s/-g.//g'`
 
-# append CPPFLAGS to both CFLAGS and CXXFLAGS
+#------------------------------------------------------------------------------
+# Use the CXXFLAGS and CFLAGS passed to configure Autoconf has defaults which
+# are not suitable for CS, so we need to filter out all -O and -g flags.
+#------------------------------------------------------------------------------
+CFLAGS=`echo "$CFLAGS" | sed 's/-O.//g;s/-g.//g'`
+CXXFLAGS=`echo "$CXXFLAGS" | sed 's/-O.//g;s/-g.//g'`
+
 cs_makefile_text="${cs_makefile_text}CFLAGS.SYSTEM = $CPPFLAGS $CFLAGS
 "
     cs_jamconfig_text="${cs_jamconfig_text}COMPILER.CFLAGS ?= \"$CPPFLAGS $CFLAGS\" ;
@@ -4450,6 +4470,8 @@ cs_makefile_text="${cs_makefile_text}LIBS.SYSTEM = $LDFLAGS
 "
     cs_jamconfig_text="${cs_jamconfig_text}COMPILER.LFLAGS ?= \"$LDFLAGS\" ;
 "
+
+
 
 #------------------------------------------------------------------------------
 # Check how to enable compilation warnings.  Note that on some platforms, it is
@@ -22973,6 +22995,32 @@ cat >>$CONFIG_STATUS <<_ACEOF
 # INIT-COMMANDS section.
 #
 
+PERL=${PERL-perl}
+		{ if test -n "$as_mkdir_p"; then
+    $as_mkdir_p include
+  else
+    as_dir=include
+    as_dirs=
+    while test ! -d "$as_dir"; do
+      as_dirs="$as_dir $as_dirs"
+      as_dir=`(dirname "$as_dir") 2>/dev/null ||
+$as_expr X"$as_dir" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
+         X"$as_dir" : 'X\(//\)[^/]' \| \
+         X"$as_dir" : 'X\(//\)$' \| \
+         X"$as_dir" : 'X\(/\)' \| \
+         .     : '\(.\)' 2>/dev/null ||
+echo X"$as_dir" |
+    sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{ s//\1/; q; }
+  	  /^X\(\/\/\)[^/].*/{ s//\1/; q; }
+  	  /^X\(\/\/\)$/{ s//\1/; q; }
+  	  /^X\(\/\).*/{ s//\1/; q; }
+  	  s/.*/./; q'`
+    done
+    test ! -n "$as_dirs" || mkdir $as_dirs
+  fi || { { echo "$as_me:$LINENO: error: cannot create directory include" >&5
+echo "$as_me: error: cannot create directory include" >&2;}
+   { (exit 1); exit 1; }; }; }
+
 cs_header_text='$cs_header_text' cs_dir=`(dirname include/volatile.h) 2>/dev/null ||
 $as_expr Xinclude/volatile.h : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
          Xinclude/volatile.h : 'X\(//\)[^/]' \| \
@@ -23097,6 +23145,7 @@ do
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "Jamfile" ) CONFIG_FILES="$CONFIG_FILES Jamfile" ;;
+  "include/csperlxs.inc" ) CONFIG_COMMANDS="$CONFIG_COMMANDS include/csperlxs.inc" ;;
   "include/volatile.h" ) CONFIG_COMMANDS="$CONFIG_COMMANDS include/volatile.h" ;;
   "config.mak" ) CONFIG_COMMANDS="$CONFIG_COMMANDS config.mak" ;;
   "Jamconfig" ) CONFIG_COMMANDS="$CONFIG_COMMANDS Jamconfig" ;;
@@ -23488,6 +23537,8 @@ ac_abs_top_srcdir=`cd "$ac_dir" && cd $ac_top_srcdir && pwd`
   { echo "$as_me:$LINENO: executing $ac_dest commands" >&5
 echo "$as_me: executing $ac_dest commands" >&6;}
   case $ac_dest in
+    include/csperlxs.inc ) $PERL -MExtUtils::Embed -e xsinit -- -o include/csperlxs.inc \
+		-std DynaLoader cspace 1>&2 ;;
     include/volatile.h ) echo $ECHO_N "$cs_header_text$ECHO_C" > $tmp/tcache
 	if diff include/volatile.h $tmp/tcache >/dev/null 2>&1; then
   { echo "$as_me:$LINENO: include/volatile.h is unchanged" >&5
