Merged trunk r25994:26094 into SoC VFS branch.
git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/branches/soc/vfs@26496 8cc4aa7f-3514-0410-904f-f2cc9021211c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1526,7 +1526,6 @@ Optional Packages:
   --with-CEGUI=dir        specify location of libCEGUI if not detected
                           automatically; searches dir/include, dir/lib, and
                           dir
-  --with-pycegui          use pycegui scripting interface (default YES)
   --with-Cg=dir           specify location of libCg if not detected
                           automatically; searches dir/include, dir/lib, and
                           dir
@@ -19410,6 +19409,186 @@ echo "${ECHO_T}$cs_cv_prog_cxx_declare_visible_hidden" >&6; }
 
 if test $cs_cv_prog_cxx_declare_visible_hidden != no; then
   cs_header_text="${cs_header_text}#define CS_VISIBILITY_HIDDEN $cs_cv_prog_cxx_declare_visible_hidden
+"
+fi
+
+
+
+
+#------------------------------------------------------------------------------
+# Check if the "malloc" attribute is available.
+#------------------------------------------------------------------------------
+{ echo "$as_me:$LINENO: checking for \"malloc\" attribute" >&5
+echo $ECHO_N "checking for \"malloc\" attribute... $ECHO_C" >&6; }
+if test "${cs_cv_prog_c_attr_malloc+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cs_cv_prog_c_attr_malloc='no'
+	if test "$cs_cv_prog_c_attr_malloc" = no; then
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+    cs_cflags_save="$CFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+
+    for cs_build_item in `echo @@@ | sed 'y% %#%'`
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
+else
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CFLAGS="$cs_cflags_test  $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
+	LIBS="$cs_libs_test  $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+__attribute__((malloc)) void f();
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cs_build_ok=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+	if test $cs_build_ok = yes; then
+  break
+fi
+
+    done
+
+
+    CFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_prog_c_attr_malloc='__attribute__((malloc))'
+else
+  cs_cv_prog_c_attr_malloc='no'
+fi
+
+fi
+
+fi
+{ echo "$as_me:$LINENO: result: $cs_cv_prog_c_attr_malloc" >&5
+echo "${ECHO_T}$cs_cv_prog_c_attr_malloc" >&6; }
+
+if test $cs_cv_prog_c_attr_malloc != no; then
+  cs_header_text="${cs_header_text}#define CS_ATTRIBUTE_MALLOC $cs_cv_prog_c_attr_malloc
 "
 fi
 
@@ -56496,471 +56675,6 @@ else
 	cs_cv_CEGUI_recent_lflags=''
 	cs_cv_CEGUI_recent_libs=''
 
-fi
-
-fi
-
-
-
-
-#------------------------------------------------------------------------------
-# Check if CEGUI Python bindings (cegui.i, cegui.py) are available, and if
-# CEGUI Python support is sufficiently recent.
-#------------------------------------------------------------------------------
-
-
-
-
-
-# Check whether --with-pycegui was given.
-if test "${with_pycegui+set}" = set; then
-  withval=$with_pycegui;
-fi
-
-if test -z "$with_pycegui"; then
-  with_pycegui=yes
-fi
-
-
-if test -n "$PYTHON" && test -n "$SWIG" &&
-    test "$with_pycegui" != no && test $cs_cv_libCEGUI = yes; then
-  if test "" != yes; then
-  { echo "$as_me:$LINENO: checking if CEGUI is bleeding edge" >&5
-echo $ECHO_N "checking if CEGUI is bleeding edge... $ECHO_C" >&6; }
-if test "${cs_cv_libCEGUI_bleeding+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_ext=cpp
-ac_cpp='$CXXCPP $CPPFLAGS'
-ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
-
-    cs_cflags_save="$CXXFLAGS"
-    cs_lflags_save="$LDFLAGS"
-    cs_libs_save="$LIBS"
-    cs_build_ok=no
-
-
-    for cs_build_item in `echo @@@ | sed 'y% %#%'`
-    do
-
-    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
-	{ for (i=1; i <= NF; ++i)
-	    { if ($i == "") print "filler"; else print $i } }'`
-    shift
-    if test $# -eq 0; then
-  cs_dummy=''
-else
-  if test "$1" = filler; then
-  cs_dummy=''
-else
-  cs_dummy=$1
-fi
-
-	shift
-fi
-if test $# -eq 0; then
-  cs_cflags_test=''
-else
-  if test "$1" = filler; then
-  cs_cflags_test=''
-else
-  cs_cflags_test=$1
-fi
-
-	shift
-fi
-if test $# -eq 0; then
-  cs_lflags_test=''
-else
-  if test "$1" = filler; then
-  cs_lflags_test=''
-else
-  cs_lflags_test=$1
-fi
-
-	shift
-fi
-if test $# -eq 0; then
-  cs_libs_test=''
-else
-  if test "$1" = filler; then
-  cs_libs_test=''
-else
-  cs_libs_test=$1
-fi
-
-	shift
-fi
-
-    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
-    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
-    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
-
-	CXXFLAGS="$cs_cflags_test $cs_cv_libCEGUI_cflags $cs_cflags_save"
-	LDFLAGS="$cs_lflags_test $cs_cv_libCEGUI_lflags $cs_lflags_save"
-	LIBS="$cs_libs_test $cs_cv_libCEGUI_libs $cs_libs_save"
-	cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <CEGUIWindow.h>
-int
-main ()
-{
-CEGUI::Window* w=new CEGUI::Window("",""); w->getXPosition();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_cxx_werror_flag" || test ! -s conftest.err'
-  { (case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_try") 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_try") 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  cs_build_ok=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-
-fi
-
-rm -f core conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-	if test $cs_build_ok = yes; then
-  break
-fi
-
-    done
-
-
-    CXXFLAGS=$cs_cflags_save
-    LDFLAGS=$cs_lflags_save
-    LIBS=$cs_libs_save
-    ac_ext=c
-ac_cpp='$CPP $CPPFLAGS'
-ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_c_compiler_gnu
-
-
-    if test $cs_build_ok = yes; then
-  cs_build_cflags=`echo x$cs_cflags_test $cs_cv_libCEGUI_cflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_build_lflags=`echo x$cs_lflags_test $cs_cv_libCEGUI_lflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_build_libs=`echo x$cs_libs_test $cs_cv_libCEGUI_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_cv_libCEGUI_bleeding=yes
-		cs_cv_libCEGUI_bleeding_cflags=$cs_build_cflags
-		cs_cv_libCEGUI_bleeding_lflags=$cs_build_lflags
-		cs_cv_libCEGUI_bleeding_libs=$cs_build_libs
-else
-  cs_cv_libCEGUI_bleeding=no
-fi
-
-fi
-{ echo "$as_me:$LINENO: result: $cs_cv_libCEGUI_bleeding" >&5
-echo "${ECHO_T}$cs_cv_libCEGUI_bleeding" >&6; }
-else
-  { echo "$as_me:$LINENO: checking if CEGUI is bleeding edge" >&5
-echo $ECHO_N "checking if CEGUI is bleeding edge... $ECHO_C" >&6; }
-	    ac_ext=cpp
-ac_cpp='$CXXCPP $CPPFLAGS'
-ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
-
-    cs_cflags_save="$CXXFLAGS"
-    cs_lflags_save="$LDFLAGS"
-    cs_libs_save="$LIBS"
-    cs_build_ok=no
-
-
-    for cs_build_item in `echo @@@ | sed 'y% %#%'`
-    do
-
-    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
-	{ for (i=1; i <= NF; ++i)
-	    { if ($i == "") print "filler"; else print $i } }'`
-    shift
-    if test $# -eq 0; then
-  cs_dummy=''
-else
-  if test "$1" = filler; then
-  cs_dummy=''
-else
-  cs_dummy=$1
-fi
-
-	shift
-fi
-if test $# -eq 0; then
-  cs_cflags_test=''
-else
-  if test "$1" = filler; then
-  cs_cflags_test=''
-else
-  cs_cflags_test=$1
-fi
-
-	shift
-fi
-if test $# -eq 0; then
-  cs_lflags_test=''
-else
-  if test "$1" = filler; then
-  cs_lflags_test=''
-else
-  cs_lflags_test=$1
-fi
-
-	shift
-fi
-if test $# -eq 0; then
-  cs_libs_test=''
-else
-  if test "$1" = filler; then
-  cs_libs_test=''
-else
-  cs_libs_test=$1
-fi
-
-	shift
-fi
-
-    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
-    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
-    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
-
-	CXXFLAGS="$cs_cflags_test $cs_cv_libCEGUI_cflags $cs_cflags_save"
-	LDFLAGS="$cs_lflags_test $cs_cv_libCEGUI_lflags $cs_lflags_save"
-	LIBS="$cs_libs_test $cs_cv_libCEGUI_libs $cs_libs_save"
-	cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <CEGUIWindow.h>
-int
-main ()
-{
-CEGUI::Window* w=new CEGUI::Window("",""); w->getXPosition();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_cxx_werror_flag" || test ! -s conftest.err'
-  { (case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_try") 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_try") 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  cs_build_ok=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-
-fi
-
-rm -f core conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-	if test $cs_build_ok = yes; then
-  break
-fi
-
-    done
-
-
-    CXXFLAGS=$cs_cflags_save
-    LDFLAGS=$cs_lflags_save
-    LIBS=$cs_libs_save
-    ac_ext=c
-ac_cpp='$CPP $CPPFLAGS'
-ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_c_compiler_gnu
-
-
-    if test $cs_build_ok = yes; then
-  cs_build_cflags=`echo x$cs_cflags_test $cs_cv_libCEGUI_cflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_build_lflags=`echo x$cs_lflags_test $cs_cv_libCEGUI_lflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_build_libs=`echo x$cs_libs_test $cs_cv_libCEGUI_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_cv_libCEGUI_bleeding=yes
-		cs_cv_libCEGUI_bleeding_cflags=$cs_build_cflags
-		cs_cv_libCEGUI_bleeding_lflags=$cs_build_lflags
-		cs_cv_libCEGUI_bleeding_libs=$cs_build_libs
-else
-  cs_cv_libCEGUI_bleeding=no
-fi
-
-	    { echo "$as_me:$LINENO: result: $cs_cv_libCEGUI_bleeding" >&5
-echo "${ECHO_T}$cs_cv_libCEGUI_bleeding" >&6; }
-fi
-
-    if test $cs_cv_libCEGUI_bleeding = yes; then
-  :
-else
-  cs_cv_libCEGUI_bleeding_cflags=''
-	cs_cv_libCEGUI_bleeding_lflags=''
-	cs_cv_libCEGUI_bleeding_libs=''
-
-fi
-
-fi
-
-
-if test "$cs_cv_libCEGUI_bleeding" = yes; then
-  { echo "$as_me:$LINENO: checking for pycegui" >&5
-echo $ECHO_N "checking for pycegui... $ECHO_C" >&6; }
-if test "${cs_cv_pycegui+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test "$with_pycegui" != yes; then
-  cs_cv_pycegui_py_file="$with_pycegui"
-else
-  cs_cv_pycegui_py_file=`{ (echo "$as_me:$LINENO: \$PYTHON -c \"import os.path
-try:
-    import cegui
-    f=getattr(cegui,'__file__')
-    print f.replace('.pyc','.py')
-except:
-    pass
-\"") >&5
-  ($PYTHON -c "import os.path
-try:
-    import cegui
-    f=getattr(cegui,'__file__')
-    print f.replace('.pyc','.py')
-except:
-    pass
-") 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } | tr '\\\\' '/' | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-fi
-
-        if test -f "$cs_cv_pycegui_py_file"; then
-  cs_cv_pycegui=yes
-else
-  cs_cv_pycegui=no
-fi
-
-fi
-{ echo "$as_me:$LINENO: result: $cs_cv_pycegui" >&5
-echo "${ECHO_T}$cs_cv_pycegui" >&6; }
-fi
-
-
-if test "$cs_cv_pycegui" = yes; then
-  { echo "$as_me:$LINENO: checking if pycegui Swig version is compatible" >&5
-echo $ECHO_N "checking if pycegui Swig version is compatible... $ECHO_C" >&6; }
-if test "${cs_cv_pycegui_swig_ok+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  pycegui_swig_ver=`{ (echo "$as_me:$LINENO: \$PYTHON -c \"import sys
-import re
-try:
-    f=open(sys.argv[1],'r')
-    s=f.readline()
-    f.close()
-    m=re.search(r'\d+\.\d+(?:\.\d+)*',s)
-    if m: print m.group()
-except:
-    pass
-\" \"\$cs_cv_pycegui_py_file\"") >&5
-  ($PYTHON -c "import sys
-import re
-try:
-    f=open(sys.argv[1],'r')
-    s=f.readline()
-    f.close()
-    m=re.search(r'\d+\.\d+(?:\.\d+)*',s)
-    if m: print m.group()
-except:
-    pass
-" "$cs_cv_pycegui_py_file") 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } | tr '\\\\' '/' | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-        if test "$pycegui_swig_ver" = "$cs_prog_swig_version"; then
-  cs_cv_pycegui_swig_ok=yes
-else
-  cs_cv_pycegui_swig_ok=no
-fi
-
-fi
-{ echo "$as_me:$LINENO: result: $cs_cv_pycegui_swig_ok" >&5
-echo "${ECHO_T}$cs_cv_pycegui_swig_ok" >&6; }
-fi
-
-
-if test "$cs_cv_pycegui_swig_ok" = yes; then
-  cs_build_prop_val="yes"
-    cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-    if test -n "$cs_build_prop_val"; then
-  cs_jamconfig_text="${cs_jamconfig_text}PYCEGUI.SWIGOK ?= \"$cs_build_prop_val\" ;
-"
 fi
 
 fi
