Eric Sunshine made the following changes:
-*- Added a check to configure.ac to determine how to disable function
    inlining.  The result of this check is used when building cspython
    since it is reported that, with some versions of GNU build tools on
    Windows, cspython fails to link and emits the error message "Error:
    0-bit reloc in dll". In particular, this occurs with optimizations
    (such as -O3) enabled. It is said that the problem can be avoided by
    disabling function inlining.  Reported by Jorg Fischer
    <turboj@web.de>.

-*- Removed the unused PTHREAD_MUTEX_TIMED test from CS_CHECK_PTHREAD() in
    checkpthread.m4.


git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/trunk@20557 8cc4aa7f-3514-0410-904f-f2cc9021211c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1446,7 +1446,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 PACKAGE_LONGNAME="Crystal Space"
-    PACKAGE_COPYRIGHT="Copyright (C)1998-2004 Jorrit Tyberghein and others"
+    PACKAGE_COPYRIGHT="Copyright (C)1998-2005 Jorrit Tyberghein and others"
     PACKAGE_HOMEPAGE="http://www.crystalspace3d.org/"
 
 
@@ -6565,163 +6565,6 @@ else
   cs_cv_sys_pthread_mutex_recursive=no
 fi
 
-    if test $cs_cv_sys_pthread = yes; then
-  echo "$as_me:$LINENO: checking for pthread timed mutexes" >&5
-echo $ECHO_N "checking for pthread timed mutexes... $ECHO_C" >&6
-if test "${cs_cv_sys_pthread_mutex_timed+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_ext=c
-ac_cpp='$CPP $CPPFLAGS'
-ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_c_compiler_gnu
-
-    cs_cflags_save="$CFLAGS"
-    cs_lflags_save="$LDFLAGS"
-    cs_libs_save="$LIBS"
-    cs_build_ok=no
-
-
-    for cs_build_item in `echo @-DCS_MUTEX_FEATURE=PTHREAD_MUTEX_TIMED@@ | sed 'y% %#%'` \
-		`echo @-DCS_MUTEX_FEATURE=PTHREAD_MUTEX_TIMED_NP@@ | sed 'y% %#%'`
-    do
-
-    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
-	{ for (i=1; i <= NF; ++i)
-	    { if ($i == "") print "filler"; else print $i } }'`
-    shift
-    if test $# -eq 0; then
-  cs_dummy=''
-else
-  if test "$1" = filler; then
-  cs_dummy=''
-else
-  cs_dummy=$1
-fi
-
-	shift
-fi
-if test $# -eq 0; then
-  cs_cflags_test=''
-else
-  if test "$1" = filler; then
-  cs_cflags_test=''
-else
-  cs_cflags_test=$1
-fi
-
-	shift
-fi
-if test $# -eq 0; then
-  cs_lflags_test=''
-else
-  if test "$1" = filler; then
-  cs_lflags_test=''
-else
-  cs_lflags_test=$1
-fi
-
-	shift
-fi
-if test $# -eq 0; then
-  cs_libs_test=''
-else
-  if test "$1" = filler; then
-  cs_libs_test=''
-else
-  cs_libs_test=$1
-fi
-
-	shift
-fi
-
-    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
-    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
-    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
-
-	CFLAGS="$cs_cflags_test $cs_cv_sys_pthread_cflags -D_GNU_SOURCE $cs_cflags_save"
-	LDFLAGS="$cs_lflags_test $cs_cv_sys_pthread_lflags $cs_lflags_save"
-	LIBS="$cs_libs_test $cs_cv_sys_pthread_libs $cs_libs_save"
-	cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <pthread.h>
-int
-main ()
-{
-pthread_mutexattr_t attr;
-		    pthread_mutexattr_settype(&attr, CS_MUTEX_FEATURE);
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  cs_build_ok=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-	if test $cs_build_ok = yes; then
-  break
-fi
-
-    done
-
-
-    CFLAGS=$cs_cflags_save
-    LDFLAGS=$cs_lflags_save
-    LIBS=$cs_libs_save
-    ac_ext=c
-ac_cpp='$CPP $CPPFLAGS'
-ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_c_compiler_gnu
-
-
-    if test $cs_build_ok = yes; then
-  cs_build_cflags=`echo x$cs_cflags_test $cs_cv_sys_pthread_cflags -D_GNU_SOURCE | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_build_lflags=`echo x$cs_lflags_test $cs_cv_sys_pthread_lflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_build_libs=`echo x$cs_libs_test $cs_cv_sys_pthread_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_cv_sys_pthread_mutex_timed=`echo $cs_build_cflags | sed 's/.*\(PTHREAD_MUTEX_TIMED_*N*P*\).*/\1/'`
-else
-  cs_cv_sys_pthread_mutex_timed=no
-fi
-
-fi
-echo "$as_me:$LINENO: result: $cs_cv_sys_pthread_mutex_timed" >&5
-echo "${ECHO_T}$cs_cv_sys_pthread_mutex_timed" >&6
-else
-  cs_cv_sys_pthread_mutex_timed=no
-fi
-
 if test "$cs_cv_sys_pthread" = yes; then
   cs_build_prop_val="yes"
     cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
@@ -7081,6 +6924,7 @@ else
 	cs_cv_sys_rtld_now_libs=''
 
 fi
+
 
 
 
@@ -7926,7 +7770,6 @@ fi
 fi
 
 fi
-
 
 
 
@@ -12768,6 +12611,179 @@ fi
 
 
 #------------------------------------------------------------------------------
+# Check if C++ function inlining can be enabled and disabled. Apparently, with
+# some versions of GNU build tools on Windows, the Crystal Space Python plugin
+# fails to link and emits the error message "Error: 0-bit reloc in dll". In
+# particular, this occurs with optimizations (such as -O3) enabled. We can
+# avoid the error by disabling function inlining.
+#------------------------------------------------------------------------------
+echo "$as_me:$LINENO: checking how to disable function inlining" >&5
+echo $ECHO_N "checking how to disable function inlining... $ECHO_C" >&6
+if test "${cs_cv_prog_cxx_disable_inlining_ok+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+    cs_cflags_save="$CXXFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+
+    for cs_build_item in `echo @-fno-inline-functions@@ | sed 'y% %#%'`
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
+else
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CXXFLAGS="$cs_cflags_test  $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
+	LIBS="$cs_libs_test  $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cs_build_ok=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+	if test $cs_build_ok = yes; then
+  break
+fi
+
+    done
+
+
+    CXXFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_prog_cxx_disable_inlining=`echo x$cs_build_cflags $cs_build_lflags $cs_build_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	    cs_cv_prog_cxx_disable_inlining_ok="$cs_cv_prog_cxx_disable_inlining"
+else
+  cs_cv_prog_cxx_disable_inlining=''
+	    cs_cv_prog_cxx_disable_inlining_ok=no
+fi
+
+fi
+echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_disable_inlining_ok" >&5
+echo "${ECHO_T}$cs_cv_prog_cxx_disable_inlining_ok" >&6
+    if test "$cs_cv_prog_cxx_disable_inlining_ok" != no; then
+  cs_build_prop_val="$cs_cv_prog_cxx_disable_inlining"
+    cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+    if test -n "$cs_build_prop_val"; then
+  cs_jamconfig_text="${cs_jamconfig_text}COMPILER.C++FLAGS.INLINING.DISABLE ?= \"$cs_build_prop_val\" ;
+"
+fi
+
+
+fi
+
+
+
+
+#------------------------------------------------------------------------------
 # Check for compiler- and CPU-specific code generation flags.  These flags are
 # mutually exclusive.  Exclusivity is enforced by the CS_CHECK_CODE_GEN_FLAG()
 # macro.  Note that use of these flags typically means that the resulting
@@ -16424,7 +16440,7 @@ fi
 
 
 #------------------------------------------------------------------------------
-# Check if va_copy or __va_copy is available.
+# Check if va_copy() or __va_copy() is available.
 #------------------------------------------------------------------------------
 # CS_CHECK_VA_COPY(FUNCTION)
 
@@ -20030,11 +20046,11 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #include <X11/Shell.h>
-		#include <X11/Xaw/Form.h>
+	    #include <X11/Xaw/Form.h>
 int
 main ()
 {
-XtVaGetValues(0, 0, 0, 0)
+XtVaGetValues(0,0,0,0)
   ;
   return 0;
 }
@@ -20182,11 +20198,11 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #include <X11/Shell.h>
-		#include <X11/Xaw/Form.h>
+	    #include <X11/Xaw/Form.h>
 int
 main ()
 {
-XtVaGetValues(0, 0, 0, 0)
+XtVaGetValues(0,0,0,0)
   ;
   return 0;
 }
@@ -20296,9 +20312,7 @@ fi
 
 fi
 
-
 fi
-
 
 
 
@@ -56965,6 +56979,7 @@ if test $enable_leak_guard = yes; then
   cs_header_text="${cs_header_text}#define CS_USE_LEAK_GUARD
 "
 fi
+
 
 
 
