Re-generated configure following r28306.
git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/trunk@28307 8cc4aa7f-3514-0410-904f-f2cc9021211c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -18225,18 +18225,21 @@ fi
 #
 # IMPLEMENTATION NOTES
 #
-# There is an obscure bug in gcc 3.4.x and at least up to 4.1.1 where
-# -fvisibility-inlines-hidden on AMD64 in combination with -fPIC and -shared
-# flags causes the linker to fail with a bogus error stating that the target
-# library needs to be built with -fPIC even when it has been built using that
-# option. On such installations, if Crystal Space is built with
-# -fvisibility-inlines-hidden, then clients liking against Crystal Space
-# experience this bogus error.  Normally, we would test for this anomaly by
-# manipulating a std::basic_string<> in a test program, and avoid
-# -fvisibility-inlines-hidden if the test program fails to link, however,
-# practical experience has shown that this test is not 100% reliable for all
-# such installations. Instead, for simplicity, we disable this flag presently
-# for gcc on AMD64.  References:
+# There is a bug in gcc 3.4.x and at least up to 4.1.x where
+# -fvisibility-inlines-hidden on several architectures in combination with
+# -fPIC and -shared flags causes the linker to fail with a bogus errors. One
+# manifestation of the error states that the target library needs to be built
+# with -fPIC even when it has been built using that option.  In other cases,
+# the linker complains about undefined references to various inline methods in
+# external libraries.  Furthre, on such installations, if Crystal Space is
+# built with -fvisibility-inlines-hidden, then clients linking against Crystal
+# Space also experience one of these bogus errors.  Thus far, the most reliable
+# way to detect this gcc bug is to test for the anomaly by manipulating a
+# std::basic_string<> in a test program linked with -fPIC and -shared, and then
+# avoid -fvisibility-inlines-hidden if the test program fails to
+# link. Practical experience has shown that this test is not 100% reliable for
+# all cases, but it does seem to catch most, and does a better job than
+# hard-coded platform and compiler version checks.  References:
 #
 #     http://dev.gentoo.org/~kugelfang/pappy-visibility.txt
 #     http://www.gnu.org/software/gcc/gcc-4.0/changes.html#visibility
@@ -18407,21 +18410,156 @@ echo "${ECHO_T}$cs_cv_prog_cxx_visibility_inlines_hidden_ok" >&6; }
 
 
 if test -n "$cs_cv_prog_cxx_visibility_inlines_hidden"; then
-  # The test below can be uncommented and adjusted once a non-buggy gcc
-    # version is found.
-    #CS_CHECK_PROG_VERSION([g++], [$CXX --version], [4.1], [9.9|.9],
-    #   [cs_cv_gxx_version_buggy=no],
-    #   [cs_cv_gxx_version_buggy=yes])
-    { echo "$as_me:$LINENO: checking if $cs_cv_prog_cxx_visibility_inlines_hidden is buggy" >&5
+  { echo "$as_me:$LINENO: checking if $cs_cv_prog_cxx_visibility_inlines_hidden is buggy" >&5
 echo $ECHO_N "checking if $cs_cv_prog_cxx_visibility_inlines_hidden is buggy... $ECHO_C" >&6; }
 if test "${cs_cv_prog_cxx_visibility_inlines_hidden_buggy+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  if test $ac_compiler_gnu = yes; then
-  if test $host_cpu = x86_64 || test x$cs_host_macosx = xyes; then
+  if test $ac_compiler_gnu = yes && test $cs_cv_libstl = yes; then
+  if test x$cs_host_macosx = xyes; then
   cs_cv_prog_cxx_visibility_inlines_hidden_buggy=yes
 else
-  cs_cv_prog_cxx_visibility_inlines_hidden_buggy=no
+  ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+    cs_cflags_save="$CXXFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+
+    for cs_build_item in `echo @$cs_cv_prog_cxx_visibility_inlines_hidden \
+			$cs_cv_prog_cxx_pic@$cs_cv_prog_link_shared@ | sed 'y% %#%'`
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
+else
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CXXFLAGS="$cs_cflags_test $cs_cv_libstl_cflags $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test $cs_cv_libstl_lflags $cs_lflags_save"
+	LIBS="$cs_libs_test $cs_cv_libstl_libs $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <string>
+int
+main ()
+{
+std::string s; s = "";
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  cs_build_ok=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+	if test $cs_build_ok = yes; then
+  break
+fi
+
+    done
+
+
+    CXXFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test $cs_cv_libstl_cflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test $cs_cv_libstl_lflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test $cs_cv_libstl_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_prog_cxx_visibility_inlines_hidden_buggy=no
+else
+  cs_cv_prog_cxx_visibility_inlines_hidden_buggy=yes
+fi
+
 fi
 
 else
@@ -18431,17 +18569,14 @@ fi
 fi
 { echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_visibility_inlines_hidden_buggy" >&5
 echo "${ECHO_T}$cs_cv_prog_cxx_visibility_inlines_hidden_buggy" >&6; }
-else
-  cs_cv_prog_cxx_visibility_inlines_hidden_buggy=no
-fi
-
-
-if test $cs_cv_prog_cxx_visibility_inlines_hidden_buggy != yes; then
+    if test $cs_cv_prog_cxx_visibility_inlines_hidden_buggy != yes; then
   cs_build_prop_val="$cs_cv_prog_cxx_visibility_inlines_hidden"
     cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
     if test -n "$cs_build_prop_val"; then
   cs_jamconfig_text="${cs_jamconfig_text}COMPILER.C++FLAGS += \"$cs_build_prop_val\" ;
 "
+fi
+
 fi
 
 fi
