Eric Sunshine made the following changes:
-*- Upgraded the documentation for csMutex and csCondition so that it
    explains that recursive mutexes are incompatible with conditions.

-*- Upgraded the various csCondition implementations so that they flag an
    error when csCondition::Wait() is invoked with a recursive mutex, thus
    enforcing the requirement that the mutex must be non-recursive.  The
    reason that the mutex must be non-recursive is because the implicit
    unlock performed by Wait() must actually release the mutex in order
    for other threads to be able to satisfy the condition. With recursive
    mutexes, there is no guarantee that unlocking the mutex actually
    releases it since it might have been locked multiple times within the
    same thread. Although most older pthread implementatons were lax about
    this requirement, more modern ones, such as NPTL, actually enforce
    it. We also now enforce this requirement.

-*- Upgraded the CS_CHECK_PTHREAD() macro in checkpython.m4 so that it
    also determines if "timed" mutexes are available, and figures out the
    actual constant representing such mutexes (usually either
    PTHREAD_MUTEX_TIMED or PTHREAD_MUTEX_TIMED_NP). If available,
    configure.ac now emits CS_PTHREAD_MUTEX_TIMED to csconfig.h with the
    appropriate value.


git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/trunk@19986 8cc4aa7f-3514-0410-904f-f2cc9021211c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6361,11 +6361,10 @@ fi
 
 	    ;;
     esac
-
     if test $cs_cv_sys_pthread = yes; then
   echo "$as_me:$LINENO: checking for pthread recursive mutexes" >&5
 echo $ECHO_N "checking for pthread recursive mutexes... $ECHO_C" >&6
-if test "${cs_cv_sys_pthread_recursive+set}" = set; then
+if test "${cs_cv_sys_pthread_mutex_recursive+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_ext=c
@@ -6380,8 +6379,8 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
     cs_build_ok=no
 
 
-    for cs_build_item in `echo @-DCS_RECURSIVE=PTHREAD_MUTEX_RECURSIVE@@ | sed 'y% %#%'` \
-		`echo @-DCS_RECURSIVE=PTHREAD_MUTEX_RECURSIVE_NP@@ | sed 'y% %#%'`
+    for cs_build_item in `echo @-DCS_MUTEX_FEATURE=PTHREAD_MUTEX_RECURSIVE@@ | sed 'y% %#%'` \
+		`echo @-DCS_MUTEX_FEATURE=PTHREAD_MUTEX_RECURSIVE_NP@@ | sed 'y% %#%'`
     do
 
     set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
@@ -6451,7 +6450,7 @@ int
 main ()
 {
 pthread_mutexattr_t attr;
-		    pthread_mutexattr_settype (&attr, CS_RECURSIVE);
+		    pthread_mutexattr_settype(&attr, CS_MUTEX_FEATURE);
   ;
   return 0;
 }
@@ -6507,17 +6506,173 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
   cs_build_cflags=`echo x$cs_cflags_test $cs_cv_sys_pthread_cflags -D_GNU_SOURCE | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
 	cs_build_lflags=`echo x$cs_lflags_test $cs_cv_sys_pthread_lflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
 	cs_build_libs=`echo x$cs_libs_test $cs_cv_sys_pthread_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_cv_sys_pthread_recursive=`echo $cs_build_cflags | \
-		    sed 's/.*\(PTHREAD_MUTEX_RECURSIVE_*N*P*\).*/\1/'`
+	cs_cv_sys_pthread_mutex_recursive=`echo $cs_build_cflags | sed 's/.*\(PTHREAD_MUTEX_RECURSIVE_*N*P*\).*/\1/'`
 else
-  cs_cv_sys_pthread_recursive=no
+  cs_cv_sys_pthread_mutex_recursive=no
 fi
 
 fi
-echo "$as_me:$LINENO: result: $cs_cv_sys_pthread_recursive" >&5
-echo "${ECHO_T}$cs_cv_sys_pthread_recursive" >&6
+echo "$as_me:$LINENO: result: $cs_cv_sys_pthread_mutex_recursive" >&5
+echo "${ECHO_T}$cs_cv_sys_pthread_mutex_recursive" >&6
 else
-  cs_cv_sys_pthread_recursive=no
+  cs_cv_sys_pthread_mutex_recursive=no
+fi
+
+    if test $cs_cv_sys_pthread = yes; then
+  echo "$as_me:$LINENO: checking for pthread timed mutexes" >&5
+echo $ECHO_N "checking for pthread timed mutexes... $ECHO_C" >&6
+if test "${cs_cv_sys_pthread_mutex_timed+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+    cs_cflags_save="$CFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+
+    for cs_build_item in `echo @-DCS_MUTEX_FEATURE=PTHREAD_MUTEX_TIMED@@ | sed 'y% %#%'` \
+		`echo @-DCS_MUTEX_FEATURE=PTHREAD_MUTEX_TIMED_NP@@ | sed 'y% %#%'`
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
+else
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CFLAGS="$cs_cflags_test $cs_cv_sys_pthread_cflags -D_GNU_SOURCE $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test $cs_cv_sys_pthread_lflags $cs_lflags_save"
+	LIBS="$cs_libs_test $cs_cv_sys_pthread_libs $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <pthread.h>
+int
+main ()
+{
+pthread_mutexattr_t attr;
+		    pthread_mutexattr_settype(&attr, CS_MUTEX_FEATURE);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cs_build_ok=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+	if test $cs_build_ok = yes; then
+  break
+fi
+
+    done
+
+
+    CFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test $cs_cv_sys_pthread_cflags -D_GNU_SOURCE | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test $cs_cv_sys_pthread_lflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test $cs_cv_sys_pthread_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_sys_pthread_mutex_timed=`echo $cs_build_cflags | sed 's/.*\(PTHREAD_MUTEX_TIMED_*N*P*\).*/\1/'`
+else
+  cs_cv_sys_pthread_mutex_timed=no
+fi
+
+fi
+echo "$as_me:$LINENO: result: $cs_cv_sys_pthread_mutex_timed" >&5
+echo "${ECHO_T}$cs_cv_sys_pthread_mutex_timed" >&6
+else
+  cs_cv_sys_pthread_mutex_timed=no
 fi
 
 if test "$cs_cv_sys_pthread" = yes; then
@@ -6544,8 +6699,13 @@ fi
 
 fi
 
-if test $cs_cv_sys_pthread_recursive != no; then
-  cs_header_text="${cs_header_text}#define CS_PTHREAD_MUTEX_RECURSIVE $cs_cv_sys_pthread_recursive
+if test $cs_cv_sys_pthread_mutex_recursive != no; then
+  cs_header_text="${cs_header_text}#define CS_PTHREAD_MUTEX_RECURSIVE $cs_cv_sys_pthread_mutex_recursive
+"
+fi
+
+if test $cs_cv_sys_pthread_mutex_timed != no; then
+  cs_header_text="${cs_header_text}#define CS_PTHREAD_MUTEX_TIMED $cs_cv_sys_pthread_mutex_timed
 "
 fi
 
