Eric Sunshine fixed the DirectDraw check in configure.ac so that it actually works.  Problem was that it was not including windows.h.  Also takes into account Jorrit's strange installation in which windows.h barfs for lack of int32.  Finally, takes Cygwin into account by checking if headers are present in /usr/include/directx.  Overall, this change fixes the problem where the Jam build system would never build the DirectDraw canvas(es) because it thought DirectDraw was unavilable.
git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/trunk@14209 8cc4aa7f-3514-0410-904f-f2cc9021211c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9896,10 +9896,13 @@ fi
 # flags are used if available.  We check for Windows opengl32 first because
 # Cygwin users often have Mesa installed, and Mesa's OpenGL library is compiled
 # without the __stdcall flags which results in link errors, whereas Microsoft's
-# native opengl32 works fine.  Finally, many OpenGL libraries on Unix already
-# contain GLX, so there is no separate GLX library, thus we first check for GLX
-# using the discovered OpenGL library before attempting to locate a separate
+# native opengl32 works fine.  Many OpenGL libraries on Unix already contain
+# GLX, so there is no separate GLX library, thus we first check for GLX using
+# the discovered OpenGL library before attempting to locate a separate
 # GLX-specific library.  The same logic is also applied to GLU and GLUT checks.
+# Finally, at least one user (Jorrit) has a strange installation in which
+# inclusion of <windows.h> fails if an int32 is not present, thus we must take
+# this into account.
 #------------------------------------------------------------------------------
 
 
@@ -11959,8 +11962,65 @@ fi
 
 
 #------------------------------------------------------------------------------
-# Check for DirectDraw.
+# Check for DirectDraw.  At least one user (Jorrit) has a strange installation
+# in which inclusion of <windows.h> fails if an int32 is not present, thus we
+# must take this into account.  With Cygwin, we must check for the DirectX
+# headers in /usr/include/directx.
 #------------------------------------------------------------------------------
+echo "$as_me:$LINENO: checking for int32" >&5
+echo $ECHO_N "checking for int32... $ECHO_C" >&6
+if test "${ac_cv_type_int32+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+int
+main ()
+{
+if ((int32 *) 0)
+  return 0;
+if (sizeof (int32))
+  return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_type_int32=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_type_int32=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_type_int32" >&5
+echo "${ECHO_T}$ac_cv_type_int32" >&6
+if test $ac_cv_type_int32 = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_TYPE_INT32 1
+_ACEOF
+
+fi
+
 if test "" != yes; then
   echo "$as_me:$LINENO: checking for DirectDraw" >&5
 echo $ECHO_N "checking for DirectDraw... $ECHO_C" >&6
@@ -11978,7 +12038,8 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
     cs_libs_save="$LIBS"
     cs_build_ok=no
 
-    for cs_build_item in `echo @@@-lddraw | sed 'y% %#%'`
+    for cs_build_item in `echo @@@-lddraw | sed 'y% %#%'` \
+    `echo @-I/usr/include/directx@@-lddraw | sed 'y% %#%'`
     do
 
     set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
@@ -12044,7 +12105,11 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <ddraw.h>
+#if !HAVE_TYPE_INT32
+	typedef long int32;
+	#endif
+	#include <windows.h>
+	#include <ddraw.h>
 int
 main ()
 {
@@ -12114,7 +12179,8 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
     cs_libs_save="$LIBS"
     cs_build_ok=no
 
-    for cs_build_item in `echo @@@-lddraw | sed 'y% %#%'`
+    for cs_build_item in `echo @@@-lddraw | sed 'y% %#%'` \
+    `echo @-I/usr/include/directx@@-lddraw | sed 'y% %#%'`
     do
 
     set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
@@ -12180,7 +12246,11 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <ddraw.h>
+#if !HAVE_TYPE_INT32
+	typedef long int32;
+	#endif
+	#include <windows.h>
+	#include <ddraw.h>
 int
 main ()
 {
