18-Jul-2007 	- Andres really made the python wrapper work (escape regex meta chars) 	  and fixes the longstanding, though propably harmless, typo in 	  checkpython.m4. Also corrects CS_CHECK_TOOL into CS_CHECK_TOOLS 	  (thanks to Eric).
git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/trunk@27240 8cc4aa7f-3514-0410-904f-f2cc9021211c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -722,6 +722,7 @@ GREP
 EGREP
 PERL
 PYTHON
+ac_ct_PYTHON
 JAVA
 JAVAC
 ANT
@@ -12274,8 +12275,10 @@ fi
 fi
 
     if test -n "$ac_tool_prefix"; then
-  # Extract the first word of "${ac_tool_prefix}python", so it can be a program name with args.
-set dummy ${ac_tool_prefix}python; ac_word=$2
+  for ac_prog in python
+  do
+    # Extract the first word of "$ac_tool_prefix$ac_prog", so it can be a program name with args.
+set dummy $ac_tool_prefix$ac_prog; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
 if test "${ac_cv_prog_PYTHON+set}" = set; then
@@ -12291,7 +12294,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_prog_PYTHON="${ac_tool_prefix}python"
+    ac_cv_prog_PYTHON="$ac_tool_prefix$ac_prog"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -12311,11 +12314,15 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
+    test -n "$PYTHON" && break
+  done
 fi
-if test -z "$ac_cv_prog_PYTHON"; then
+if test -z "$PYTHON"; then
   ac_ct_PYTHON=$PYTHON
-  # Extract the first word of "python", so it can be a program name with args.
-set dummy python; ac_word=$2
+  for ac_prog in python
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
 if test "${ac_cv_prog_ac_ct_PYTHON+set}" = set; then
@@ -12331,7 +12338,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_prog_ac_ct_PYTHON="python"
+    ac_cv_prog_ac_ct_PYTHON="$ac_prog"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -12350,6 +12357,10 @@ else
 echo "${ECHO_T}no" >&6; }
 fi
 
+
+  test -n "$ac_ct_PYTHON" && break
+done
+
   if test "x$ac_ct_PYTHON" = x; then
     PYTHON=""
   else
@@ -12365,8 +12376,6 @@ ac_tool_warned=yes ;;
 esac
     PYTHON=$ac_ct_PYTHON
   fi
-else
-  PYTHON="$ac_cv_prog_PYTHON"
 fi
 
 
@@ -12467,8 +12476,7 @@ fi
 
 	    if test -n "$cs_pyver" &&
 		   test -n "$cs_cv_pybase_cflags" &&
-		   test -n "$cs_cv_pybase_lflags$cs_cv_pybase_sysprefix_lflags" \
-		   	-o .pyd = "$cs_cv_python_ext"; then
+		   test -n "$cs_cv_pybase_lflags_base$cs_cv_pybase_sysprefix_lflags"; then
   cs_cv_python_sdk=yes
 else
   cs_cv_python_sdk=no
@@ -79308,6 +79316,7 @@ GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
 PERL!$PERL$ac_delim
 PYTHON!$PYTHON$ac_delim
+ac_ct_PYTHON!$ac_ct_PYTHON$ac_delim
 JAVA!$JAVA$ac_delim
 JAVAC!$JAVAC$ac_delim
 ANT!$ANT$ac_delim
@@ -79396,7 +79405,6 @@ ac_ct_CONFIG_CPPUNIT!$ac_ct_CONFIG_CPPUNIT$ac_delim
 CONFIG_BFD!$CONFIG_BFD$ac_delim
 ac_ct_CONFIG_BFD!$ac_ct_CONFIG_BFD$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
-LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -79431,6 +79439,50 @@ N; s/^.*\n//; s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g; b n
 ' >>$CONFIG_STATUS <conf$$subs.sed
 rm -f conf$$subs.sed
 cat >>$CONFIG_STATUS <<_ACEOF
+CEOF$ac_eof
+_ACEOF
+
+
+ac_delim='%!_!# '
+for ac_last_try in false false false false false :; do
+  cat >conf$$subs.sed <<_ACEOF
+LTLIBOBJS!$LTLIBOBJS$ac_delim
+_ACEOF
+
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 1; then
+    break
+  elif $ac_last_try; then
+    { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
+echo "$as_me: error: could not make $CONFIG_STATUS" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    ac_delim="$ac_delim!$ac_delim _$ac_delim!! "
+  fi
+done
+
+ac_eof=`sed -n '/^CEOF[0-9]*$/s/CEOF/0/p' conf$$subs.sed`
+if test -n "$ac_eof"; then
+  ac_eof=`echo "$ac_eof" | sort -nru | sed 1q`
+  ac_eof=`expr $ac_eof + 1`
+fi
+
+cat >>$CONFIG_STATUS <<_ACEOF
+cat >"\$tmp/subs-3.sed" <<\CEOF$ac_eof
+/@[a-zA-Z_][a-zA-Z_0-9]*@/!b end
+_ACEOF
+sed '
+s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g
+s/^/s,@/; s/!/@,|#_!!_#|/
+:n
+t n
+s/'"$ac_delim"'$/,g/; t
+s/$/\\/; p
+N; s/^.*\n//; s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g; b n
+' >>$CONFIG_STATUS <conf$$subs.sed
+rm -f conf$$subs.sed
+cat >>$CONFIG_STATUS <<_ACEOF
+:end
+s/|#_!!_#|//g
 CEOF$ac_eof
 _ACEOF
 
@@ -79668,7 +79720,7 @@ s&@builddir@&$ac_builddir&;t t
 s&@abs_builddir@&$ac_abs_builddir&;t t
 s&@abs_top_builddir@&$ac_abs_top_builddir&;t t
 $ac_datarootdir_hack
-" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed -f "$tmp/subs-2.sed" | sed 's/|#_!!_#|//g' >$tmp/out
+" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed -f "$tmp/subs-2.sed" | sed -f "$tmp/subs-3.sed" >$tmp/out
 
 test -z "$ac_datarootdir_hack$ac_datarootdir_seen" &&
   { ac_out=`sed -n '/\${datarootdir}/p' "$tmp/out"`; test -n "$ac_out"; } &&
