svn-commit.tmp
git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/trunk@24315 8cc4aa7f-3514-0410-904f-f2cc9021211c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13753,8 +13753,8 @@ fi
 # (e.g. not linking against some library, a missing function) that could cause
 # problems on stricter platforms.
 #------------------------------------------------------------------------------
-echo "$as_me:$LINENO: checking if warning for missing symbols is supported" >&5
-echo $ECHO_N "checking if warning for missing symbols is supported... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking if reporting missing symbols is supported" >&5
+echo $ECHO_N "checking if reporting missing symbols is supported... $ECHO_C" >&6
 if test "${cs_cv_prog_link_z_defs_ok+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
@@ -13916,6 +13916,179 @@ fi
 
 fi
 
+echo "$as_me:$LINENO: checking if missing symbols can be reported as warnings" >&5
+echo $ECHO_N "checking if missing symbols can be reported as warnings... $ECHO_C" >&6
+if test "${cs_cv_prog_link_warn_unresolved_symbols_ok+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+    cs_cflags_save="$CXXFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+
+    for cs_build_item in `echo @@-Wl,--warn-unresolved-symbols@ | sed 'y% %#%'`
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
+else
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CXXFLAGS="$cs_cflags_test  $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
+	LIBS="$cs_libs_test  $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cs_build_ok=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+	if test $cs_build_ok = yes; then
+  break
+fi
+
+    done
+
+
+    CXXFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_prog_link_warn_unresolved_symbols=`echo x$cs_build_cflags $cs_build_lflags $cs_build_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	    cs_cv_prog_link_warn_unresolved_symbols_ok="$cs_cv_prog_link_warn_unresolved_symbols"
+else
+  cs_cv_prog_link_warn_unresolved_symbols=''
+	    cs_cv_prog_link_warn_unresolved_symbols_ok=no
+fi
+
+fi
+echo "$as_me:$LINENO: result: $cs_cv_prog_link_warn_unresolved_symbols_ok" >&5
+echo "${ECHO_T}$cs_cv_prog_link_warn_unresolved_symbols_ok" >&6
+    if test "$cs_cv_prog_link_warn_unresolved_symbols_ok" != no; then
+  cs_build_prop_val="$cs_cv_prog_link_warn_unresolved_symbols"
+    cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+    if test -n "$cs_build_prop_val"; then
+  cs_jamconfig_text="${cs_jamconfig_text}COMPILER.LFLAGS += \"$cs_build_prop_val\" ;
+"
+fi
+
+
+fi
+
+
+
+
+#------------------------------------------------------------------------------
+# Check if linker recognizes "--as-needed" which only links dynamic libs that
+# are really honestly needed.
+#------------------------------------------------------------------------------
+#CS_EMIT_BUILD_FLAGS([if --as-needed is supported],
+#    [cs_cv_prog_link_as_needed], [CS_CREATE_TUPLE([],[-Wl,--as-needed])],
+#    [C++], [COMPILER.LFLAGS], [+])
 
 
 
@@ -18773,8 +18946,8 @@ fi
 #------------------------------------------------------------------------------
 binutils_recent=no
 if test -n "$OBJCOPY"; then
-  echo "$as_me:$LINENO: checking if binutils version >= 2.16" >&5
-echo $ECHO_N "checking if binutils version >= 2.16... $ECHO_C" >&6
+  echo "$as_me:$LINENO: checking if binutils version >= 2.16.0" >&5
+echo $ECHO_N "checking if binutils version >= 2.16.0... $ECHO_C" >&6
 if test "${cs_cv_prog_binutils_version_ok_annotated+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
@@ -18791,19 +18964,19 @@ cs_prog_binutils_min_suffix_done=
 test -z $cs_prog_binutils_is_version && cs_prog_binutils_is_version=`$OBJCOPY -V | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/;q'`
 test -n "$cs_prog_binutils_is_version" && test -z $cs_prog_binutils_is_suffix_done  && { cs_prog_binutils_is_suffix_done=yes ; cs_prog_binutils_is_suffix= ; }
 
-test -z $cs_prog_binutils_is_version && cs_prog_binutils_is_version=`$OBJCOPY -V | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/;q'`
-test -n "$cs_prog_binutils_is_version" && test -z $cs_prog_binutils_is_suffix_done  && { cs_prog_binutils_is_suffix_done=yes ; cs_prog_binutils_is_suffix=.0.0.0 ; }
+test -z $cs_prog_binutils_is_version && cs_prog_binutils_is_version=`$OBJCOPY -V | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/;q'`
+test -n "$cs_prog_binutils_is_version" && test -z $cs_prog_binutils_is_suffix_done  && { cs_prog_binutils_is_suffix_done=yes ; cs_prog_binutils_is_suffix=.0.0 ; }
 
 
 
 
 
 
-test -z $cs_prog_binutils_min_version && cs_prog_binutils_min_version=`echo 2.16 | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/;q'`
+test -z $cs_prog_binutils_min_version && cs_prog_binutils_min_version=`echo 2.16.0 | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/;q'`
 test -n "$cs_prog_binutils_min_version" && test -z $cs_prog_binutils_min_suffix_done  && { cs_prog_binutils_min_suffix_done=yes ; cs_prog_binutils_min_suffix= ; }
 
-test -z $cs_prog_binutils_min_version && cs_prog_binutils_min_version=`echo 2.16 | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/;q'`
-test -n "$cs_prog_binutils_min_version" && test -z $cs_prog_binutils_min_suffix_done  && { cs_prog_binutils_min_suffix_done=yes ; cs_prog_binutils_min_suffix=.0.0.0 ; }
+test -z $cs_prog_binutils_min_version && cs_prog_binutils_min_version=`echo 2.16.0 | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/;q'`
+test -n "$cs_prog_binutils_min_version" && test -z $cs_prog_binutils_min_suffix_done  && { cs_prog_binutils_min_suffix_done=yes ; cs_prog_binutils_min_suffix=.0.0 ; }
 
 
 cs_prog_binutils_is_ver_1=`echo ${cs_prog_binutils_is_version}${cs_prog_binutils_is_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1/'`
@@ -22807,7 +22980,7 @@ fi
 
 	CFLAGS="$cs_cflags_test $X_CFLAGS $cs_cflags_save"
 	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
-	LIBS="$cs_libs_test $X_PRE_LIBS $X_LIBS -lX11 $X_EXTRA_LIBS $cs_libs_save"
+	LIBS="$cs_libs_test $X_PRE_LIBS $X_LIBS -lXt -lX11 $X_EXTRA_LIBS $cs_libs_save"
 	cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -22874,7 +23047,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
     if test $cs_build_ok = yes; then
   cs_build_cflags=`echo x$cs_cflags_test $X_CFLAGS | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
 	cs_build_lflags=`echo x$cs_lflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_build_libs=`echo x$cs_libs_test $X_PRE_LIBS $X_LIBS -lX11 $X_EXTRA_LIBS | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test $X_PRE_LIBS $X_LIBS -lXt -lX11 $X_EXTRA_LIBS | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
 	cs_cv_libXaw=yes
 		cs_cv_libXaw_cflags=$cs_build_cflags
 		cs_cv_libXaw_lflags=$cs_build_lflags
@@ -22959,7 +23132,7 @@ fi
 
 	CFLAGS="$cs_cflags_test $X_CFLAGS $cs_cflags_save"
 	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
-	LIBS="$cs_libs_test $X_PRE_LIBS $X_LIBS -lX11 $X_EXTRA_LIBS $cs_libs_save"
+	LIBS="$cs_libs_test $X_PRE_LIBS $X_LIBS -lXt -lX11 $X_EXTRA_LIBS $cs_libs_save"
 	cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -23026,7 +23199,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
     if test $cs_build_ok = yes; then
   cs_build_cflags=`echo x$cs_cflags_test $X_CFLAGS | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
 	cs_build_lflags=`echo x$cs_lflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_build_libs=`echo x$cs_libs_test $X_PRE_LIBS $X_LIBS -lX11 $X_EXTRA_LIBS | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test $X_PRE_LIBS $X_LIBS -lXt -lX11 $X_EXTRA_LIBS | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
 	cs_cv_libXaw=yes
 		cs_cv_libXaw_cflags=$cs_build_cflags
 		cs_cv_libXaw_lflags=$cs_build_lflags
