Regenerated configure following r28746.
git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/trunk@28747 8cc4aa7f-3514-0410-904f-f2cc9021211c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -18871,6 +18871,7 @@ fi
 echo "${ECHO_T}$cs_cv_prog_cxx_pic_ok" >&6; }
 
 
+# Check if compiler recognizes an option to set inline visibility to hidden.
 { echo "$as_me:$LINENO: checking for inline visibility flag" >&5
 echo $ECHO_N "checking for inline visibility flag... $ECHO_C" >&6; }
 if test "${cs_cv_prog_cxx_visibility_inlines_hidden_ok+set}" = set; then
@@ -19024,6 +19025,332 @@ echo "${ECHO_T}$cs_cv_prog_cxx_visibility_inlines_hidden_ok" >&6; }
 
 cs_prog_cxx_visibility_inlines_hidden=$cs_cv_prog_cxx_visibility_inlines_hidden
 
+# Check if compiler silently accepts option but later complains that
+# "visibility attribute is not supported in this configuration".
+if test -n "$cs_prog_cxx_visibility_inlines_hidden"; then
+  if test "" != yes; then
+  { echo "$as_me:$LINENO: checking if configuration supports $cs_prog_cxx_visibility_inlines_hidden" >&5
+echo $ECHO_N "checking if configuration supports $cs_prog_cxx_visibility_inlines_hidden... $ECHO_C" >&6; }
+if test "${cs_cv_prog_cxx_visibility_inlines_hidden_supported+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+    cs_cflags_save="$CXXFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+
+    for cs_build_item in `echo @@@ | sed 'y% %#%'`
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
+else
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CXXFLAGS="$cs_cflags_test $cs_prog_cxx_visibility_inlines_hidden \
+        $cs_cv_prog_cxx_enable_errors $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
+	LIBS="$cs_libs_test  $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+template <typename T> struct X { inline void f() {} };
+int
+main ()
+{
+X<int>().f();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  cs_build_ok=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+	if test $cs_build_ok = yes; then
+  break
+fi
+
+    done
+
+
+    CXXFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test $cs_prog_cxx_visibility_inlines_hidden \
+        $cs_cv_prog_cxx_enable_errors | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_prog_cxx_visibility_inlines_hidden_supported=yes
+		cs_cv_prog_cxx_visibility_inlines_hidden_supported_cflags=$cs_build_cflags
+		cs_cv_prog_cxx_visibility_inlines_hidden_supported_lflags=$cs_build_lflags
+		cs_cv_prog_cxx_visibility_inlines_hidden_supported_libs=$cs_build_libs
+else
+  cs_cv_prog_cxx_visibility_inlines_hidden_supported=no
+fi
+
+fi
+{ echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_visibility_inlines_hidden_supported" >&5
+echo "${ECHO_T}$cs_cv_prog_cxx_visibility_inlines_hidden_supported" >&6; }
+else
+  { echo "$as_me:$LINENO: checking if configuration supports $cs_prog_cxx_visibility_inlines_hidden" >&5
+echo $ECHO_N "checking if configuration supports $cs_prog_cxx_visibility_inlines_hidden... $ECHO_C" >&6; }
+	    ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+    cs_cflags_save="$CXXFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+
+    for cs_build_item in `echo @@@ | sed 'y% %#%'`
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
+else
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CXXFLAGS="$cs_cflags_test $cs_prog_cxx_visibility_inlines_hidden \
+        $cs_cv_prog_cxx_enable_errors $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
+	LIBS="$cs_libs_test  $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+template <typename T> struct X { inline void f() {} };
+int
+main ()
+{
+X<int>().f();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  cs_build_ok=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+	if test $cs_build_ok = yes; then
+  break
+fi
+
+    done
+
+
+    CXXFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test $cs_prog_cxx_visibility_inlines_hidden \
+        $cs_cv_prog_cxx_enable_errors | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_prog_cxx_visibility_inlines_hidden_supported=yes
+		cs_cv_prog_cxx_visibility_inlines_hidden_supported_cflags=$cs_build_cflags
+		cs_cv_prog_cxx_visibility_inlines_hidden_supported_lflags=$cs_build_lflags
+		cs_cv_prog_cxx_visibility_inlines_hidden_supported_libs=$cs_build_libs
+else
+  cs_cv_prog_cxx_visibility_inlines_hidden_supported=no
+fi
+
+	    { echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_visibility_inlines_hidden_supported" >&5
+echo "${ECHO_T}$cs_cv_prog_cxx_visibility_inlines_hidden_supported" >&6; }
+fi
+
+    if test $cs_cv_prog_cxx_visibility_inlines_hidden_supported = yes; then
+  cs_cv_prog_cxx_visibility_inlines_hidden_supported=yes
+else
+  cs_cv_prog_cxx_visibility_inlines_hidden_supported_cflags=''
+	cs_cv_prog_cxx_visibility_inlines_hidden_supported_lflags=''
+	cs_cv_prog_cxx_visibility_inlines_hidden_supported_libs=''
+	cs_cv_prog_cxx_visibility_inlines_hidden_supported=no
+fi
+
+    if test $cs_cv_prog_cxx_visibility_inlines_hidden_supported != yes; then
+  cs_prog_cxx_visibility_inlines_hidden=''
+fi
+
+fi
+
+
+# Check if hidden visibility handling is buggy.
 if test -n "$cs_prog_cxx_visibility_inlines_hidden"; then
   { echo "$as_me:$LINENO: checking if $cs_prog_cxx_visibility_inlines_hidden is buggy" >&5
 echo $ECHO_N "checking if $cs_prog_cxx_visibility_inlines_hidden is buggy... $ECHO_C" >&6; }
