- Vincent regenerated configure following r28592.
git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/branches/release/V1.2@28593 8cc4aa7f-3514-0410-904f-f2cc9021211c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -16434,7 +16434,7 @@ fi
 
 
 #------------------------------------------------------------------------------
-# Check if "hidden" visibilty for inline functions is supported.
+# Check how to declare symbol visibility.
 #------------------------------------------------------------------------------
 echo "$as_me:$LINENO: checking how to treat C warnings as errors" >&5
 echo $ECHO_N "checking how to treat C warnings as errors... $ECHO_C" >&6
@@ -17398,14 +17398,9 @@ fi
 
 
 
-
-#------------------------------------------------------------------------------
-# Check how to set default symbol visibility, and how to override the setting
-# in code.
-#------------------------------------------------------------------------------
-echo "$as_me:$LINENO: checking for \"hidden\" symbol visibility flag" >&5
-echo $ECHO_N "checking for \"hidden\" symbol visibility flag... $ECHO_C" >&6
-if test "${cs_cv_prog_cc_visibility_hidden_ok+set}" = set; then
+echo "$as_me:$LINENO: checking for hidden symbol visibility flag" >&5
+echo $ECHO_N "checking for hidden symbol visibility flag... $ECHO_C" >&6
+if test "${cs_cv_prog_c_visibility_hidden_ok+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_ext=c
@@ -17476,7 +17471,7 @@ fi
     cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
     cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
 
-	CFLAGS="$cs_cflags_test  $cs_cflags_save"
+	CFLAGS="$cs_cflags_test $cs_cv_prog_c_enable_errors $cs_cflags_save"
 	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
 	LIBS="$cs_libs_test  $cs_libs_save"
 	cat >conftest.$ac_ext <<_ACEOF
@@ -17545,19 +17540,18 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
   cs_build_cflags=`echo x$cs_cflags_test | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
 	cs_build_lflags=`echo x$cs_lflags_test | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
 	cs_build_libs=`echo x$cs_libs_test | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_cv_prog_cc_visibility_hidden=`echo x$cs_build_cflags $cs_build_lflags $cs_build_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	    cs_cv_prog_cc_visibility_hidden_ok="$cs_cv_prog_cc_visibility_hidden"
+	cs_cv_prog_c_visibility_hidden=`echo x$cs_build_cflags $cs_build_lflags $cs_build_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	    cs_cv_prog_c_visibility_hidden_ok="$cs_cv_prog_c_visibility_hidden"
 else
-  cs_cv_prog_cc_visibility_hidden=''
-	    cs_cv_prog_cc_visibility_hidden_ok=no
+  cs_cv_prog_c_visibility_hidden=''
+	    cs_cv_prog_c_visibility_hidden_ok=no
 fi
 
 fi
-echo "$as_me:$LINENO: result: $cs_cv_prog_cc_visibility_hidden_ok" >&5
-echo "${ECHO_T}$cs_cv_prog_cc_visibility_hidden_ok" >&6
-
-if test -n "$cs_cv_prog_cc_visibility_hidden"; then
-  cs_build_prop_val="$cs_cv_prog_cc_visibility_hidden"
+echo "$as_me:$LINENO: result: $cs_cv_prog_c_visibility_hidden_ok" >&5
+echo "${ECHO_T}$cs_cv_prog_c_visibility_hidden_ok" >&6
+    if test "$cs_cv_prog_c_visibility_hidden_ok" != no; then
+  cs_build_prop_val="$cs_cv_prog_c_visibility_hidden"
     cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
     if test -n "$cs_build_prop_val"; then
   cs_jamconfig_text="${cs_jamconfig_text}COMPILER.CFLAGS += \"$cs_build_prop_val\" ;
@@ -17567,9 +17561,10 @@ fi
 fi
 
 
-echo "$as_me:$LINENO: checking for \"default\" symbol visibility flag" >&5
-echo $ECHO_N "checking for \"default\" symbol visibility flag... $ECHO_C" >&6
-if test "${cs_cv_prog_cc_visibility_default_ok+set}" = set; then
+
+echo "$as_me:$LINENO: checking for default symbol visibility flag" >&5
+echo $ECHO_N "checking for default symbol visibility flag... $ECHO_C" >&6
+if test "${cs_cv_prog_c_visibility_default_ok+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_ext=c
@@ -17640,7 +17635,7 @@ fi
     cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
     cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
 
-	CFLAGS="$cs_cflags_test  $cs_cflags_save"
+	CFLAGS="$cs_cflags_test $cs_cv_prog_c_enable_errors $cs_cflags_save"
 	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
 	LIBS="$cs_libs_test  $cs_libs_save"
 	cat >conftest.$ac_ext <<_ACEOF
@@ -17709,19 +17704,18 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
   cs_build_cflags=`echo x$cs_cflags_test | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
 	cs_build_lflags=`echo x$cs_lflags_test | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
 	cs_build_libs=`echo x$cs_libs_test | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_cv_prog_cc_visibility_default=`echo x$cs_build_cflags $cs_build_lflags $cs_build_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	    cs_cv_prog_cc_visibility_default_ok="$cs_cv_prog_cc_visibility_default"
+	cs_cv_prog_c_visibility_default=`echo x$cs_build_cflags $cs_build_lflags $cs_build_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	    cs_cv_prog_c_visibility_default_ok="$cs_cv_prog_c_visibility_default"
 else
-  cs_cv_prog_cc_visibility_default=''
-	    cs_cv_prog_cc_visibility_default_ok=no
+  cs_cv_prog_c_visibility_default=''
+	    cs_cv_prog_c_visibility_default_ok=no
 fi
 
 fi
-echo "$as_me:$LINENO: result: $cs_cv_prog_cc_visibility_default_ok" >&5
-echo "${ECHO_T}$cs_cv_prog_cc_visibility_default_ok" >&6
-
-if test -n "$cs_cv_prog_cc_visibility_default"; then
-  cs_build_prop_val="$cs_cv_prog_cc_visibility_default"
+echo "$as_me:$LINENO: result: $cs_cv_prog_c_visibility_default_ok" >&5
+echo "${ECHO_T}$cs_cv_prog_c_visibility_default_ok" >&6
+    if test "$cs_cv_prog_c_visibility_default_ok" != no; then
+  cs_build_prop_val="$cs_cv_prog_c_visibility_default"
     cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
     if test -n "$cs_build_prop_val"; then
   cs_jamconfig_text="${cs_jamconfig_text}COMPILER.CFLAGS.VISIBILITY_DEFAULT ?= \"$cs_build_prop_val\" ;
@@ -17731,174 +17725,13 @@ fi
 fi
 
 
-echo "$as_me:$LINENO: checking how to declare default visibility" >&5
-echo $ECHO_N "checking how to declare default visibility... $ECHO_C" >&6
-if test "${cs_cv_prog_cxx_declare_visible_def+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  cs_cv_prog_cxx_declare_visible_def='no'
-	if test "$cs_cv_prog_cxx_declare_visible_def" = no; then
-  ac_ext=cc
-ac_cpp='$CXXCPP $CPPFLAGS'
-ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
-
-    cs_cflags_save="$CXXFLAGS"
-    cs_lflags_save="$LDFLAGS"
-    cs_libs_save="$LIBS"
-    cs_build_ok=no
-
-
-    for cs_build_item in `echo @@@ | sed 'y% %#%'`
-    do
-
-    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
-	{ for (i=1; i <= NF; ++i)
-	    { if ($i == "") print "filler"; else print $i } }'`
-    shift
-    if test $# -eq 0; then
-  cs_dummy=''
-else
-  if test "$1" = filler; then
-  cs_dummy=''
-else
-  cs_dummy=$1
-fi
-
-	shift
-fi
-if test $# -eq 0; then
-  cs_cflags_test=''
-else
-  if test "$1" = filler; then
-  cs_cflags_test=''
-else
-  cs_cflags_test=$1
-fi
-
-	shift
-fi
-if test $# -eq 0; then
-  cs_lflags_test=''
-else
-  if test "$1" = filler; then
-  cs_lflags_test=''
-else
-  cs_lflags_test=$1
-fi
-
-	shift
-fi
-if test $# -eq 0; then
-  cs_libs_test=''
-else
-  if test "$1" = filler; then
-  cs_libs_test=''
-else
-  cs_libs_test=$1
-fi
-
-	shift
-fi
-
-    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
-    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
-    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
-
-	CXXFLAGS="$cs_cflags_test  $cs_cflags_save"
-	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
-	LIBS="$cs_libs_test  $cs_libs_save"
-	cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-__attribute__((visibility("default"))) void f();
-int
-main ()
-{
-
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_cxx_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  cs_build_ok=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-	if test $cs_build_ok = yes; then
-  break
-fi
-
-    done
-
-
-    CXXFLAGS=$cs_cflags_save
-    LDFLAGS=$cs_lflags_save
-    LIBS=$cs_libs_save
-    ac_ext=c
-ac_cpp='$CPP $CPPFLAGS'
-ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_c_compiler_gnu
-
-
-    if test $cs_build_ok = yes; then
-  cs_build_cflags=`echo x$cs_cflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_build_lflags=`echo x$cs_lflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_build_libs=`echo x$cs_libs_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_cv_prog_cxx_declare_visible_def='__attribute__((visibility("default")))'
-else
-  cs_cv_prog_cxx_declare_visible_def='no'
-fi
-
-fi
-
-fi
-echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_declare_visible_def" >&5
-echo "${ECHO_T}$cs_cv_prog_cxx_declare_visible_def" >&6
-
-if test $cs_cv_prog_cxx_declare_visible_def != no; then
-  cs_header_text="${cs_header_text}#define CS_VISIBILITY_DEFAULT $cs_cv_prog_cxx_declare_visible_def
-"
-fi
-
-
 echo "$as_me:$LINENO: checking how to declare hidden visibility" >&5
 echo $ECHO_N "checking how to declare hidden visibility... $ECHO_C" >&6
-if test "${cs_cv_prog_cxx_declare_visible_hidden+set}" = set; then
+if test "${cs_cv_prog_cxx_declare_visibility_hidden+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  cs_cv_prog_cxx_declare_visible_hidden='no'
-	if test "$cs_cv_prog_cxx_declare_visible_hidden" = no; then
+  cs_cv_prog_cxx_declare_visibility_hidden='no'
+	if test "$cs_cv_prog_cxx_declare_visibility_hidden" = no; then
   ac_ext=cc
 ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -18036,19 +17869,178 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
   cs_build_cflags=`echo x$cs_cflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
 	cs_build_lflags=`echo x$cs_lflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
 	cs_build_libs=`echo x$cs_libs_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_cv_prog_cxx_declare_visible_hidden='__attribute__((visibility("hidden")))'
+	cs_cv_prog_cxx_declare_visibility_hidden='__attribute__((visibility("hidden")))'
 else
-  cs_cv_prog_cxx_declare_visible_hidden='no'
+  cs_cv_prog_cxx_declare_visibility_hidden='no'
 fi
 
 fi
 
 fi
-echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_declare_visible_hidden" >&5
-echo "${ECHO_T}$cs_cv_prog_cxx_declare_visible_hidden" >&6
+echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_declare_visibility_hidden" >&5
+echo "${ECHO_T}$cs_cv_prog_cxx_declare_visibility_hidden" >&6
+    if test $cs_cv_prog_cxx_declare_visibility_hidden != no; then
+  cs_header_text="${cs_header_text}#define CS_VISIBILITY_HIDDEN $cs_cv_prog_cxx_declare_visibility_hidden
+"
+fi
 
-if test $cs_cv_prog_cxx_declare_visible_hidden != no; then
-  cs_header_text="${cs_header_text}#define CS_VISIBILITY_HIDDEN $cs_cv_prog_cxx_declare_visible_hidden
+
+echo "$as_me:$LINENO: checking how to declare default visibility" >&5
+echo $ECHO_N "checking how to declare default visibility... $ECHO_C" >&6
+if test "${cs_cv_prog_cxx_declare_visibility_default+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cs_cv_prog_cxx_declare_visibility_default='no'
+	if test "$cs_cv_prog_cxx_declare_visibility_default" = no; then
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+    cs_cflags_save="$CXXFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+
+    for cs_build_item in `echo @@@ | sed 'y% %#%'`
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
+else
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CXXFLAGS="$cs_cflags_test  $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
+	LIBS="$cs_libs_test  $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+__attribute__((visibility("default"))) void f();
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cs_build_ok=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+	if test $cs_build_ok = yes; then
+  break
+fi
+
+    done
+
+
+    CXXFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_prog_cxx_declare_visibility_default='__attribute__((visibility("default")))'
+else
+  cs_cv_prog_cxx_declare_visibility_default='no'
+fi
+
+fi
+
+fi
+echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_declare_visibility_default" >&5
+echo "${ECHO_T}$cs_cv_prog_cxx_declare_visibility_default" >&6
+    if test $cs_cv_prog_cxx_declare_visibility_default != no; then
+  cs_header_text="${cs_header_text}#define CS_VISIBILITY_DEFAULT $cs_cv_prog_cxx_declare_visibility_default
 "
 fi
 
