Eric Sunshine made the following changes to the configure script:
-*- Fixed bug: The utility variable cs_optimize_flags was being
    constructed incorrectly, with the result that it was always empty,
    rather than containing the detected optimization flags.

-*- Removed the bogus qsqrt(1)==0 test which was supposed to detect buggy
    gcc 3.2.x.  It turns out that Matze made an error in his trials
    (printing a float with an int format directive), thus his results were
    invalid.

-*- The special-case -fPIC directive for the qsqrt() check is now used
    only if the compiler understands -fPIC.

-*- Documented Matze's -fPIC assumption.  (Please keep the comments
    up-to-date.)

-*- The libpng test now employs -lm (if available) since it is reported
    that RedHat 8.x requires this library.


git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/trunk@13042 8cc4aa7f-3514-0410-904f-f2cc9021211c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6131,7 +6131,7 @@ fi
 echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_optimize" >&5
 echo "${ECHO_T}$cs_cv_prog_cxx_optimize" >&6
     if test "$cs_cv_prog_cxx_optimize" != no; then
-  cs_optimize_flags="$cs_optimize_flags $cs_build_cflags"
+  cs_optimize_flags="$cs_optimize_flags $cs_cv_prog_cxx_optimize"
 	cs_makefile_text="${cs_makefile_text}CFLAGS.optimize += $cs_cv_prog_cxx_optimize
 "
 else
@@ -6274,7 +6274,8 @@ fi
 echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_omit_frame_pointer" >&5
 echo "${ECHO_T}$cs_cv_prog_cxx_omit_frame_pointer" >&6
     if test "$cs_cv_prog_cxx_omit_frame_pointer" != no; then
-  cs_optimize_flags="$cs_optimize_flags $cs_build_cflags"
+  cs_optimize_flags="$cs_optimize_flags \
+	    $cs_cv_prog_cxx_omit_frame_pointer"
 	cs_makefile_text="${cs_makefile_text}CFLAGS.optimize += $cs_cv_prog_cxx_omit_frame_pointer
 "
 else
@@ -6417,7 +6418,7 @@ fi
 echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_fast_math" >&5
 echo "${ECHO_T}$cs_cv_prog_cxx_fast_math" >&6
     if test "$cs_cv_prog_cxx_fast_math" != no; then
-  cs_optimize_flags="$cs_optimize_flags $cs_build_cflags"
+  cs_optimize_flags="$cs_optimize_flags $cs_cv_prog_cxx_fast_math"
 	cs_makefile_text="${cs_makefile_text}CFLAGS.optimize += $cs_cv_prog_cxx_fast_math
 "
 else
@@ -11752,9 +11753,13 @@ fi
 
 #------------------------------------------------------------------------------
 # Check for libpng.  In addition to the standard installed locations, we also
-# search CS/libs/libpng*.
+# search CS/libs/libpng*.  Some platforms, such as RedHat 8.x require libm.a to
+# be linked with libpng, so use libm.a if available.
 #------------------------------------------------------------------------------
+
+
 if test "$cs_cv_libz" = yes; then
+
 
 # Check whether --with-libpng or --without-libpng was given.
 if test "${with_libpng+set}" = set; then
@@ -11950,9 +11955,9 @@ fi
     cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
     cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
 
-	CFLAGS="$cs_cflags_test $cs_cv_libz_cflags $cs_cflags_save"
-	LDFLAGS="$cs_lflags_test $cs_cv_libz_lflags $cs_lflags_save"
-	LIBS="$cs_libs_test $cs_cv_libz_libs $cs_libs_save"
+	CFLAGS="$cs_cflags_test $cs_cv_libz_cflags $cs_cv_libm_cflags $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test $cs_cv_libz_lflags $cs_cv_libm_lflags $cs_lflags_save"
+	LIBS="$cs_libs_test $cs_cv_libz_libs $cs_cv_libm_libs $cs_libs_save"
 	cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -12001,9 +12006,9 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
     if test $cs_build_ok = yes; then
-  cs_build_cflags=`echo x$cs_cflags_test $cs_cv_libz_cflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_build_lflags=`echo x$cs_lflags_test $cs_cv_libz_lflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_build_libs=`echo x$cs_libs_test $cs_cv_libz_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+  cs_build_cflags=`echo x$cs_cflags_test $cs_cv_libz_cflags $cs_cv_libm_cflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test $cs_cv_libz_lflags $cs_cv_libm_lflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test $cs_cv_libz_libs $cs_cv_libm_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
 	cs_cv_libpng=yes
 		cs_cv_libpng_cflags=$cs_build_cflags
 		cs_cv_libpng_lflags=$cs_build_lflags
@@ -12085,9 +12090,9 @@ fi
     cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
     cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
 
-	CFLAGS="$cs_cflags_test $cs_cv_libz_cflags $cs_cflags_save"
-	LDFLAGS="$cs_lflags_test $cs_cv_libz_lflags $cs_lflags_save"
-	LIBS="$cs_libs_test $cs_cv_libz_libs $cs_libs_save"
+	CFLAGS="$cs_cflags_test $cs_cv_libz_cflags $cs_cv_libm_cflags $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test $cs_cv_libz_lflags $cs_cv_libm_lflags $cs_lflags_save"
+	LIBS="$cs_libs_test $cs_cv_libz_libs $cs_cv_libm_libs $cs_libs_save"
 	cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -12136,9 +12141,9 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
     if test $cs_build_ok = yes; then
-  cs_build_cflags=`echo x$cs_cflags_test $cs_cv_libz_cflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_build_lflags=`echo x$cs_lflags_test $cs_cv_libz_lflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_build_libs=`echo x$cs_libs_test $cs_cv_libz_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+  cs_build_cflags=`echo x$cs_cflags_test $cs_cv_libz_cflags $cs_cv_libm_cflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test $cs_cv_libz_lflags $cs_cv_libm_lflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test $cs_cv_libz_libs $cs_cv_libm_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
 	cs_cv_libpng=yes
 		cs_cv_libpng_cflags=$cs_build_cflags
 		cs_cv_libpng_lflags=$cs_build_lflags
@@ -16861,6 +16866,8 @@ fi
 
 
 
+
+
 #------------------------------------------------------------------------------
 # Check for libxml2
 #------------------------------------------------------------------------------
@@ -16955,6 +16962,8 @@ echo "${ECHO_T}yes" >&6
   else
      :
   fi
+
+
 
 
 #------------------------------------------------------------------------------
@@ -19774,10 +19783,11 @@ fi
 #	Check if gcc is able to understand CS/include/qsqrt.h.  This test will
 #	catch not only versions of gcc which do not understand the assembly
 #	content, but also buggy versions which fail with an internal error on
-#	this file (such as the RedHat 7 gcc).  Furthermore, check if qsqrt()
-#	actually returns reasonable results with compiler optimizations
-#	enabled, since it is reported that some versions of gcc 3.2.x return
-#	incorrect results, such as qsqrt(1)=0.  Sets the shell variable
+#	this file (such as the RedHat 7 gcc).  Furthermore, it is reported that
+#	some versions of gcc 3.2.x cause qsqrt() to return bogus results when
+#	compiled in optimize mode.  It is reported that this same compiler
+#	crashes with an internal error when -fPIC is used, so we use -fPIC as a
+#	way to detect this buggy compiler.  Sets the shell variable
 #	cs_cv_cxx_qsqrt_ok to "yes" if qsqrt.h is usable, otherwise "no".
 #------------------------------------------------------------------------------
 
@@ -19786,9 +19796,9 @@ fi
 
 
     if test $ac_compiler_gnu = yes; then
-  echo "$as_me:$LINENO: checking if qsqrt() is usable" >&5
-echo $ECHO_N "checking if qsqrt() is usable... $ECHO_C" >&6
-if test "${cs_cv_cxx_qsqrt_ok+set}" = set; then
+  echo "$as_me:$LINENO: checking if $CXX recognizes -fPIC" >&5
+echo $ECHO_N "checking if $CXX recognizes -fPIC... $ECHO_C" >&6
+if test "${cs_cv_prog_cxx_fpic+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_ext=cc
@@ -19797,12 +19807,210 @@ ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
-	    cs_cflags_save="$CXXFLAGS"
-	    CXXFLAGS="$CXXFLAGS -fPIC $cs_optimize_flags"
-	    if test "$cross_compiling" = yes; then
-  cs_cv_cxx_qsqrt_ok=no
+    cs_cflags_save="$CXXFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+    for cs_build_item in `echo @-fPIC@@ | sed 'y% %#%'`
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
 else
-  cat >conftest.$ac_ext <<_ACEOF
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CXXFLAGS="$cs_cflags_test  $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
+	LIBS="$cs_libs_test  $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cs_build_ok=yes break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+    done
+
+    CXXFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_prog_cxx_fpic=-fPIC
+else
+  cs_cv_prog_cxx_fpic=no
+fi
+
+fi
+echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_fpic" >&5
+echo "${ECHO_T}$cs_cv_prog_cxx_fpic" >&6
+	echo "$as_me:$LINENO: checking if qsqrt() compiles" >&5
+echo $ECHO_N "checking if qsqrt() compiles... $ECHO_C" >&6
+if test "${cs_cv_cxx_qsqrt_ok+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cs_qsqrt_cflags="$cs_optimize_flags"
+	    if test $cs_cv_prog_cxx_fpic != no; then
+  cs_qsqrt_cflags="$cs_qsqrt_cflags $cs_cv_prog_cxx_fpic"
+fi
+
+	    ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+    cs_cflags_save="$CXXFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+    for cs_build_item in `echo @$cs_qsqrt_cflags@@ | sed 'y% %#%'`
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
+else
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CXXFLAGS="$cs_cflags_test  $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
+	LIBS="$cs_libs_test  $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
 _ACEOF
@@ -19815,39 +20023,50 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
-float n = qsqrt(1); exit (n == 0);
+float n = qsqrt(1.0f); (void)n;
   ;
   return 0;
 }
 _ACEOF
-rm -f conftest$ac_exeext
+rm -f conftest.$ac_objext conftest$ac_exeext
 if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  cs_cv_cxx_qsqrt_ok=yes
+  cs_build_ok=yes break
 else
-  echo "$as_me: program exited with status $ac_status" >&5
-echo "$as_me: failed program was:" >&5
+  echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-( exit $ac_status )
-cs_cv_cxx_qsqrt_ok=no
 fi
-rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
-fi
-	    CXXFLAGS="$cs_cflags_save"
-	    ac_ext=c
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+    done
+
+    CXXFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_cxx_qsqrt_ok=yes
+else
+  cs_cv_cxx_qsqrt_ok=no
+fi
 
 fi
 echo "$as_me:$LINENO: result: $cs_cv_cxx_qsqrt_ok" >&5
