Eric Sunshine upgraded the cal3d check in configure.ac so that it checks for the very recent version required by CS.
git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/trunk@15137 8cc4aa7f-3514-0410-904f-f2cc9021211c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19510,6 +19510,292 @@ fi
     cs_cv_with_libcal3d="$with_libcal3d"
 
     if test "$cs_cv_libcal3d" = yes; then
+  :
+else
+  :
+fi
+
+
+if test $cs_cv_libcal3d = yes; then
+  if test "" != yes; then
+  echo "$as_me:$LINENO: checking if cal3d is sufficiently recent" >&5
+echo $ECHO_N "checking if cal3d is sufficiently recent... $ECHO_C" >&6
+if test "${cs_cv_cal3d_recent+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+    cs_cflags_save="$CXXFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+    for cs_build_item in `echo @@@ | sed 'y% %#%'`
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
+else
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CXXFLAGS="$cs_cflags_test  $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
+	LIBS="$cs_libs_test  $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <cal3d/cal3d.h>
+	    #include <string>
+int
+main ()
+{
+std::string s(""); CalCoreModel m; m.addAnimHelper(s,0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cs_build_ok=yes
+	    break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+    done
+
+    CXXFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_cal3d_recent=yes
+		cs_cv_cal3d_recent_cflags=$cs_build_cflags
+		cs_cv_cal3d_recent_lflags=$cs_build_lflags
+		cs_cv_cal3d_recent_libs=$cs_build_libs
+else
+  cs_cv_cal3d_recent=no
+fi
+
+fi
+echo "$as_me:$LINENO: result: $cs_cv_cal3d_recent" >&5
+echo "${ECHO_T}$cs_cv_cal3d_recent" >&6
+else
+  echo "$as_me:$LINENO: checking if cal3d is sufficiently recent" >&5
+echo $ECHO_N "checking if cal3d is sufficiently recent... $ECHO_C" >&6
+	    ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+    cs_cflags_save="$CXXFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+    for cs_build_item in `echo @@@ | sed 'y% %#%'`
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
+else
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CXXFLAGS="$cs_cflags_test  $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
+	LIBS="$cs_libs_test  $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <cal3d/cal3d.h>
+	    #include <string>
+int
+main ()
+{
+std::string s(""); CalCoreModel m; m.addAnimHelper(s,0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cs_build_ok=yes
+	    break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+    done
+
+    CXXFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_cal3d_recent=yes
+		cs_cv_cal3d_recent_cflags=$cs_build_cflags
+		cs_cv_cal3d_recent_lflags=$cs_build_lflags
+		cs_cv_cal3d_recent_libs=$cs_build_libs
+else
+  cs_cv_cal3d_recent=no
+fi
+
+	    echo "$as_me:$LINENO: result: $cs_cv_cal3d_recent" >&5
+echo "${ECHO_T}$cs_cv_cal3d_recent" >&6
+fi
+
+    if test $cs_cv_cal3d_recent = yes; then
   if test "$cs_cv_libcal3d" = yes; then
   cs_makefile_text="${cs_makefile_text}CAL3D.AVAILABLE = yes
 "
@@ -19533,18 +19819,24 @@ fi
 
 fi
 
-	cs_makefile_text="${cs_makefile_text}HAS_CAL3D = yes
+	    cs_makefile_text="${cs_makefile_text}HAS_CAL3D = yes
 "
 else
-  :
+  cs_cv_cal3d_recent_cflags=''
+	cs_cv_cal3d_recent_lflags=''
+	cs_cv_cal3d_recent_libs=''
+	:
 fi
+
+fi
+
 
 
 
 #------------------------------------------------------------------------------
 # Check for SDL
+# @@@ FIXME We should probably use sdl-config.
 #------------------------------------------------------------------------------
-# XXX: We should use sdl-config...
 
 # Check whether --with-libSDL or --without-libSDL was given.
 if test "${with_libSDL+set}" = set; then
@@ -19982,11 +20274,12 @@ fi
 
 fi
 
-	    cs_makefile_text="${cs_makefile_text}HAS_SDL = yes
+	cs_makefile_text="${cs_makefile_text}HAS_SDL = yes
 "
 else
   :
 fi
+
 
 
 
@@ -20302,6 +20595,8 @@ else
 	cs_cv_sys_linux_joystick_libs=''
 	:
 fi
+
+
 
 
 #------------------------------------------------------------------------------
@@ -20749,6 +21044,8 @@ else
 fi
 
 
+
+
 #------------------------------------------------------------------------------
 # Check if objcopy is present (part of GNU binutils).
 #------------------------------------------------------------------------------
@@ -20802,6 +21099,8 @@ if test -n "$OBJCOPY"; then
     cs_jamconfig_text="${cs_jamconfig_text}CMD.OBJCOPY ?= \"$OBJCOPY\" ;
 "
 fi
+
+
 
 
 #------------------------------------------------------------------------------
