Eric Sunshine added an automated check to configure.ac to test for presence of the Linux joystick API.  The test is based upon a code fragment provided by Norman Kraemer.  This test obsoletes the --enable-linux-joystick switch.
git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/trunk@13903 8cc4aa7f-3514-0410-904f-f2cc9021211c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -870,7 +870,6 @@ Optional Features:
                           Pentium-specific code will not run on an Intel 486)
   --disable-freetypetest  Do not try to compile and run
                           a test FreeType program
-  --enable-linux-joystick enable Linux joystick support (default NO)
   --enable-optimize       build with optimizations enabled (default YES); same
                           as --enable-mode=optimize
   --enable-debug          build with debugging information (default NO); same
@@ -19428,6 +19427,322 @@ fi
 
 
 #------------------------------------------------------------------------------
+# Check if Linux joystick API is present.
+#------------------------------------------------------------------------------
+if test "" != yes; then
+  echo "$as_me:$LINENO: checking for Linux joystick API" >&5
+echo $ECHO_N "checking for Linux joystick API... $ECHO_C" >&6
+if test "${cs_cv_sys_linux_joystick+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+    cs_cflags_save="$CFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+    for cs_build_item in `echo @@@ | sed 'y% %#%'`
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
+else
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CFLAGS="$cs_cflags_test  $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
+	LIBS="$cs_libs_test  $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <fcntl.h>
+	#include <linux/joystick.h>
+int
+main ()
+{
+unsigned char axes;
+	unsigned char buttons;
+	int version;
+	char name[128];
+	int fd;
+	struct js_event js;
+	(void)js;
+	ioctl(fd, JSIOCGVERSION, &version);
+	ioctl(fd, JSIOCGAXES, &axes);
+	ioctl(fd, JSIOCGBUTTONS, &buttons);
+	ioctl(fd, JSIOCGNAME(128), name);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cs_build_ok=yes
+	    break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+    done
+
+    CFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_sys_linux_joystick=yes
+		cs_cv_sys_linux_joystick_cflags=$cs_build_cflags
+		cs_cv_sys_linux_joystick_lflags=$cs_build_lflags
+		cs_cv_sys_linux_joystick_libs=$cs_build_libs
+else
+  cs_cv_sys_linux_joystick=no
+fi
+
+fi
+echo "$as_me:$LINENO: result: $cs_cv_sys_linux_joystick" >&5
+echo "${ECHO_T}$cs_cv_sys_linux_joystick" >&6
+else
+  echo "$as_me:$LINENO: checking for Linux joystick API" >&5
+echo $ECHO_N "checking for Linux joystick API... $ECHO_C" >&6
+	    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+    cs_cflags_save="$CFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+    for cs_build_item in `echo @@@ | sed 'y% %#%'`
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
+else
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CFLAGS="$cs_cflags_test  $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
+	LIBS="$cs_libs_test  $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <fcntl.h>
+	#include <linux/joystick.h>
+int
+main ()
+{
+unsigned char axes;
+	unsigned char buttons;
+	int version;
+	char name[128];
+	int fd;
+	struct js_event js;
+	(void)js;
+	ioctl(fd, JSIOCGVERSION, &version);
+	ioctl(fd, JSIOCGAXES, &axes);
+	ioctl(fd, JSIOCGBUTTONS, &buttons);
+	ioctl(fd, JSIOCGNAME(128), name);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cs_build_ok=yes
+	    break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+    done
+
+    CFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_sys_linux_joystick=yes
+		cs_cv_sys_linux_joystick_cflags=$cs_build_cflags
+		cs_cv_sys_linux_joystick_lflags=$cs_build_lflags
+		cs_cv_sys_linux_joystick_libs=$cs_build_libs
+else
+  cs_cv_sys_linux_joystick=no
+fi
+
+	    echo "$as_me:$LINENO: result: $cs_cv_sys_linux_joystick" >&5
+echo "${ECHO_T}$cs_cv_sys_linux_joystick" >&6
+fi
+
+    if test $cs_cv_sys_linux_joystick = yes; then
+  cs_makefile_text="${cs_makefile_text}LINUXJOYSTICK.AVAILABLE = yes
+"
+    cs_jamconfig_text="${cs_jamconfig_text}LINUXJOYSTICK.AVAILABLE ?= \"yes\" ;
+"
+else
+  cs_cv_sys_linux_joystick_cflags=''
+	cs_cv_sys_linux_joystick_lflags=''
+	cs_cv_sys_linux_joystick_libs=''
+	:
+fi
+
+
+
+
+#------------------------------------------------------------------------------
 # Determine if plugin modules must implement main().  This is needed on some
 # platforms to ensure that global constructors and functions which initialize
 # global variables in the plugin module get invoked.
@@ -22110,30 +22425,6 @@ echo "$as_me:$LINENO: result: $cs_cv_cxx_qint_ok" >&5
 echo "${ECHO_T}$cs_cv_cxx_qint_ok" >&6
 if test $cs_cv_cxx_qint_ok = no; then
   cs_header_text="${cs_header_text}#define CS_QINT_WORKAROUND
-"
-fi
-
-
-
-
-#------------------------------------------------------------------------------
-# Check if Linux joystick plugin should be built.
-#------------------------------------------------------------------------------
-echo "$as_me:$LINENO: checking whether to enable Linux joystick support" >&5
-echo $ECHO_N "checking whether to enable Linux joystick support... $ECHO_C" >&6
-# Check whether --enable-linux-joystick or --disable-linux-joystick was given.
-if test "${enable_linux_joystick+set}" = set; then
-  enableval="$enable_linux_joystick"
-
-else
-  enable_linux_joystick=no
-fi;
-echo "$as_me:$LINENO: result: $enable_linux_joystick" >&5
-echo "${ECHO_T}$enable_linux_joystick" >&6
-if test "$enable_linux_joystick" != no; then
-  cs_makefile_text="${cs_makefile_text}LINUXJOYSTICK.AVAILABLE = yes
-"
-    cs_jamconfig_text="${cs_jamconfig_text}LINUXJOYSTICK.AVAILABLE ?= \"yes\" ;
 "
 fi
 
