Eric Sunshine made the following changes:
-*- Changed the socket support check in the configure script so that it no
    longer includes both <winsock.h> and the Unix socket-related headers
    at the same time even if both are present.  This works around a
    problem with Cygwin where including <winsock.h> and Unix
    socket-related headers causes the test to fail because the same
    functions and structures are defined differently between <winsock.h>
    and the other headers.

-*- Changed the <winsock.h> check in the configure script so that it no
    longer uses AC_CHECK_HEADERS's "default-includes" when checking for
    presence of this file.  This works around a problem on Cygwin where
    structures and functions are defined differently between <winsock.h>
    and <sys/types.h> and <unistd.h>, all of which are present with
    Cygwin.


git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/migrated/branches/R0_96@13059 8cc4aa7f-3514-0410-904f-f2cc9021211c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -18902,12 +18902,70 @@ fi
 
 #------------------------------------------------------------------------------
 # Check for BSD-style socket support.  Also test for presence of type
-# socklen_t.  Note that we must not include both <winsock.h> and <sys/socket.h>
-# at the same time on Cygwin even though they both exist since the inclusion of
-# both files generates a lot of errors.  Therefore, if <winsock.h> is present,
-# we include only it, otherwise we include <sys/socket.h>.
+# socklen_t.  Note that we must not include both <winsock.h> and the Unix
+# socket-related headers at the same time on Cygwin even though they both exist
+# since the inclusion of both results in errors about structures and functions
+# defined differently between <winsock.h> and the other headers.  Therefore, if
+# <winsock.h> is present, we include only it, otherwise we include the Unix
+# socket-related headers.  A related problem also occurs with the check for
+# presence of <winsock.h> on Cygwin, thus this check is handled specially.  For
+# this check, the "default-includes" normally used by AC_CHECK_HEADER() are
+# suppressed.  This prevents complaints about structures and functions in
+# <winsock.h> being defined differently by <sys/types.h> and <unistd.h>
 #------------------------------------------------------------------------------
 
+
+
+for ac_header in winsock.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* no default includes */
+
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_Header=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "$as_ac_Header=no"
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+
+done
 
 
 
@@ -18923,8 +18981,7 @@ for ac_header in unistd.h \
     sys/ioctl.h \
     netinet/in.h \
     arpa/inet.h \
-    netdb.h \
-    winsock.h
+    netdb.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -19152,7 +19209,10 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#if HAVE_SYS_TYPES_H
+#if HAVE_WINSOCK_H
+	#include <winsock.h>
+	#else
+	#if HAVE_SYS_TYPES_H
 	#include <sys/types.h>
 	#endif
 	#if HAVE_NETINET_IN_H
@@ -19161,10 +19221,9 @@ cat >>conftest.$ac_ext <<_ACEOF
 	#if HAVE_ARPA_INET_H
 	#include <arpa/inet.h>
 	#endif
-	#if HAVE_WINSOCK_H
-	#include <winsock.h>
-	#elif HAVE_SYS_SOCKET_H
+	#if HAVE_SYS_SOCKET_H
 	#include <sys/socket.h>
+	#endif
 	#endif
 int
 main ()
@@ -19303,7 +19362,10 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#if HAVE_SYS_TYPES_H
+#if HAVE_WINSOCK_H
+	#include <winsock.h>
+	#else
+	#if HAVE_SYS_TYPES_H
 	#include <sys/types.h>
 	#endif
 	#if HAVE_NETINET_IN_H
@@ -19312,10 +19374,9 @@ cat >>conftest.$ac_ext <<_ACEOF
 	#if HAVE_ARPA_INET_H
 	#include <arpa/inet.h>
 	#endif
-	#if HAVE_WINSOCK_H
-	#include <winsock.h>
-	#elif HAVE_SYS_SOCKET_H
+	#if HAVE_SYS_SOCKET_H
 	#include <sys/socket.h>
+	#endif
 	#endif
 int
 main ()
@@ -19412,24 +19473,23 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #if HAVE_UNISTD_H
-    #include <unistd.h>
-    #endif
-    #if HAVE_SYS_TYPES_H
-    #include <sys/types.h>
-    #endif
-    #if HAVE_SYS_SOCKET_H
-    #include <sys/socket.h>
-    #endif
-    #if HAVE_SYS_IOCTL_H
-    #include <sys/ioctl.h>
-    #endif
-    #if HAVE_NETINET_IN_H
-    #include <netinet/in.h>
-    #endif
-    #if HAVE_NETDB_H
-    #include <netdb.h>
-    #endif
-
+	#include <unistd.h>
+	#endif
+	#if HAVE_SYS_TYPES_H
+	#include <sys/types.h>
+	#endif
+	#if HAVE_SYS_SOCKET_H
+	#include <sys/socket.h>
+	#endif
+	#if HAVE_SYS_IOCTL_H
+	#include <sys/ioctl.h>
+	#endif
+	#if HAVE_NETINET_IN_H
+	#include <netinet/in.h>
+	#endif
+	#if HAVE_NETDB_H
+	#include <netdb.h>
+	#endif
 
 int
 main ()
