Eric Sunshine augmented the qsqrt() test in configure.ac so that it also now checks for bogus results from qsqrt() in optimize mode, rather than only testing if it compiles.  This is needed because some versions of gcc 3.2.x return incorrect results in optimize mode, such as qsqrt(1)=0.
git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/trunk@12748 8cc4aa7f-3514-0410-904f-f2cc9021211c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -870,8 +870,6 @@ Optional Features:
                           Pentium-specific code will not run on an Intel 486)
   --disable-freetypetest  Do not try to compile and run
                           a test FreeType program
-  --enable-qsqrt          enable qsqrt() optimization (may not work with some
-                          compilers) (default YES)
   --enable-linux-joystick enable Linux joystick support (default NO)
   --enable-optimize       build with optimizations enabled (default YES); same
                           as --enable-mode=optimize
@@ -4115,8 +4113,11 @@ fi
 echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_enable_warnings" >&5
 echo "${ECHO_T}$cs_cv_prog_cxx_enable_warnings" >&6
     if test "$cs_cv_prog_cxx_enable_warnings" != no; then
-  cs_makefile_text="${cs_makefile_text}CFLAGS.SYSTEM += $cs_cv_prog_cxx_enable_warnings
+
+	cs_makefile_text="${cs_makefile_text}CFLAGS.SYSTEM += $cs_cv_prog_cxx_enable_warnings
 "
+else
+  :
 fi
 
 
@@ -4401,8 +4402,11 @@ fi
 echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_disable_pragma_warnings" >&5
 echo "${ECHO_T}$cs_cv_prog_cxx_disable_pragma_warnings" >&6
     if test "$cs_cv_prog_cxx_disable_pragma_warnings" != no; then
-  cs_makefile_text="${cs_makefile_text}CFLAGS.SYSTEM += $cs_cv_prog_cxx_disable_pragma_warnings
+
+	cs_makefile_text="${cs_makefile_text}CFLAGS.SYSTEM += $cs_cv_prog_cxx_disable_pragma_warnings
 "
+else
+  :
 fi
 
 
@@ -4546,8 +4550,11 @@ fi
 echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_disable_exceptions" >&5
 echo "${ECHO_T}$cs_cv_prog_cxx_disable_exceptions" >&6
     if test "$cs_cv_prog_cxx_disable_exceptions" != no; then
-  cs_makefile_text="${cs_makefile_text}CFLAGS.SYSTEM += $cs_cv_prog_cxx_disable_exceptions
+
+	cs_makefile_text="${cs_makefile_text}CFLAGS.SYSTEM += $cs_cv_prog_cxx_disable_exceptions
 "
+else
+  :
 fi
 
 
@@ -4694,8 +4701,11 @@ fi
 echo "$as_me:$LINENO: result: $cs_cv_prog_link_suppress_multiple" >&5
 echo "${ECHO_T}$cs_cv_prog_link_suppress_multiple" >&6
     if test "$cs_cv_prog_link_suppress_multiple" != no; then
-  cs_makefile_text="${cs_makefile_text}MACOSX.LFLAGS.CONFIG += $cs_cv_prog_link_suppress_multiple
+
+	cs_makefile_text="${cs_makefile_text}MACOSX.LFLAGS.CONFIG += $cs_cv_prog_link_suppress_multiple
 "
+else
+  :
 fi
 
 
@@ -4848,8 +4858,11 @@ fi
 echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_vtable_thunks" >&5
 echo "${ECHO_T}$cs_cv_prog_cxx_vtable_thunks" >&6
     if test "$cs_cv_prog_cxx_vtable_thunks" != no; then
-  cs_makefile_text="${cs_makefile_text}CFLAGS.SYSTEM += $cs_cv_prog_cxx_vtable_thunks
+
+	cs_makefile_text="${cs_makefile_text}CFLAGS.SYSTEM += $cs_cv_prog_cxx_vtable_thunks
 "
+else
+  :
 fi
 
 	    ;;
@@ -5976,7 +5989,14 @@ fi
 #------------------------------------------------------------------------------
 # Check for compiler optimization flags.
 #------------------------------------------------------------------------------
-echo "$as_me:$LINENO: checking how to enable optimizations" >&5
+
+
+
+
+
+    cs_optimize_flags=''
+
+    echo "$as_me:$LINENO: checking how to enable optimizations" >&5
 echo $ECHO_N "checking how to enable optimizations... $ECHO_C" >&6
 if test "${cs_cv_prog_cxx_optimize+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -6111,12 +6131,15 @@ fi
 echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_optimize" >&5
 echo "${ECHO_T}$cs_cv_prog_cxx_optimize" >&6
     if test "$cs_cv_prog_cxx_optimize" != no; then
-  cs_makefile_text="${cs_makefile_text}CFLAGS.optimize += $cs_cv_prog_cxx_optimize
+  cs_optimize_flags="$cs_optimize_flags $cs_build_cflags"
+	cs_makefile_text="${cs_makefile_text}CFLAGS.optimize += $cs_cv_prog_cxx_optimize
 "
+else
+  :
 fi
 
 
-echo "$as_me:$LINENO: checking if $CXX recognizes -fomit-frame-pointer" >&5
+    echo "$as_me:$LINENO: checking if $CXX recognizes -fomit-frame-pointer" >&5
 echo $ECHO_N "checking if $CXX recognizes -fomit-frame-pointer... $ECHO_C" >&6
 if test "${cs_cv_prog_cxx_omit_frame_pointer+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -6251,12 +6274,15 @@ fi
 echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_omit_frame_pointer" >&5
 echo "${ECHO_T}$cs_cv_prog_cxx_omit_frame_pointer" >&6
     if test "$cs_cv_prog_cxx_omit_frame_pointer" != no; then
-  cs_makefile_text="${cs_makefile_text}CFLAGS.optimize += $cs_cv_prog_cxx_omit_frame_pointer
+  cs_optimize_flags="$cs_optimize_flags $cs_build_cflags"
+	cs_makefile_text="${cs_makefile_text}CFLAGS.optimize += $cs_cv_prog_cxx_omit_frame_pointer
 "
+else
+  :
 fi
 
 
-echo "$as_me:$LINENO: checking if $CXX recognizes -ffast-math" >&5
+    echo "$as_me:$LINENO: checking if $CXX recognizes -ffast-math" >&5
 echo $ECHO_N "checking if $CXX recognizes -ffast-math... $ECHO_C" >&6
 if test "${cs_cv_prog_cxx_fast_math+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -6391,8 +6417,11 @@ fi
 echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_fast_math" >&5
 echo "${ECHO_T}$cs_cv_prog_cxx_fast_math" >&6
     if test "$cs_cv_prog_cxx_fast_math" != no; then
-  cs_makefile_text="${cs_makefile_text}CFLAGS.optimize += $cs_cv_prog_cxx_fast_math
+  cs_optimize_flags="$cs_optimize_flags $cs_build_cflags"
+	cs_makefile_text="${cs_makefile_text}CFLAGS.optimize += $cs_cv_prog_cxx_fast_math
 "
+else
+  :
 fi
 
 
@@ -6536,8 +6565,11 @@ fi
 echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_debug" >&5
 echo "${ECHO_T}$cs_cv_prog_cxx_debug" >&6
     if test "$cs_cv_prog_cxx_debug" != no; then
-  cs_makefile_text="${cs_makefile_text}CFLAGS.debug += $cs_cv_prog_cxx_debug
+
+	cs_makefile_text="${cs_makefile_text}CFLAGS.debug += $cs_cv_prog_cxx_debug
 "
+else
+  :
 fi
 
 if test $cs_cv_prog_cxx_debug != no; then
@@ -19349,25 +19381,20 @@ fi
 #	Check if gcc is able to understand CS/include/qsqrt.h.  This test will
 #	catch not only versions of gcc which do not understand the assembly
 #	content, but also buggy versions which fail with an internal error on
-#	this file (such as the RedHat 7 gcc).  Sets the shell variable
-#	cs_cv_cxx_qsqrt_ok to "yes" if qsqrt.h is compilable, otherwise "no".
+#	this file (such as the RedHat 7 gcc).  Furthermore, check if qsqrt()
+#	actually returns reasonable results with compiler optimizations
+#	enabled, since it is reported that some versions of gcc 3.2.x return
+#	incorrect results, such as qsqrt(1)=0.  Sets the shell variable
+#	cs_cv_cxx_qsqrt_ok to "yes" if qsqrt.h is usable, otherwise "no".
 #------------------------------------------------------------------------------
 
 
-# Check whether --enable-qsqrt or --disable-qsqrt was given.
-if test "${enable_qsqrt+set}" = set; then
-  enableval="$enable_qsqrt"
 
-else
-  enable_qsqrt=yes
-fi;
-
-if test $enable_qsqrt = yes; then
 
 
     if test $ac_compiler_gnu = yes; then
-  echo "$as_me:$LINENO: checking if qsqrt() compiles" >&5
-echo $ECHO_N "checking if qsqrt() compiles... $ECHO_C" >&6
+  echo "$as_me:$LINENO: checking if qsqrt() is usable" >&5
+echo $ECHO_N "checking if qsqrt() is usable... $ECHO_C" >&6
 if test "${cs_cv_cxx_qsqrt_ok+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
@@ -19377,71 +19404,12 @@ ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
-    cs_cflags_save="$CXXFLAGS"
-    cs_lflags_save="$LDFLAGS"
-    cs_libs_save="$LIBS"
-    cs_build_ok=no
-
-    for cs_build_item in `echo @@@ | sed 'y% %#%'`
-    do
-
-    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
-	{ for (i=1; i <= NF; ++i)
-	    { if ($i == "") print "filler"; else print $i } }'`
-    shift
-    if test $# -eq 0; then
-  cs_dummy=''
+	    cs_cflags_save="$CXXFLAGS"
+	    CXXFLAGS="$CXXFLAGS $cs_optimize_flags"
+	    if test "$cross_compiling" = yes; then
+  cs_cv_cxx_qsqrt_ok=no
 else
-  if test "$1" = filler; then
-  cs_dummy=''
-else
-  cs_dummy=$1
-fi
-
-	shift
-fi
-if test $# -eq 0; then
-  cs_cflags_test=''
-else
-  if test "$1" = filler; then
-  cs_cflags_test=''
-else
-  cs_cflags_test=$1
-fi
-
-	shift
-fi
-if test $# -eq 0; then
-  cs_lflags_test=''
-else
-  if test "$1" = filler; then
-  cs_lflags_test=''
-else
-  cs_lflags_test=$1
-fi
-
-	shift
-fi
-if test $# -eq 0; then
-  cs_libs_test=''
-else
-  if test "$1" = filler; then
-  cs_libs_test=''
-else
-  cs_libs_test=$1
-fi
-
-	shift
-fi
-
-    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
-    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
-    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
-
-	CXXFLAGS="$cs_cflags_test  $cs_cflags_save"
-	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
-	LIBS="$cs_libs_test  $cs_libs_save"
-	cat >conftest.$ac_ext <<_ACEOF
+  cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
 _ACEOF
@@ -19454,58 +19422,43 @@ cat >>conftest.$ac_ext <<_ACEOF
 int
 main ()
 {
-float n = qsqrt(1.0f); (void)n;
+float n = qsqrt(1); exit (n == 0);
   ;
   return 0;
 }
 _ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
+rm -f conftest$ac_exeext
 if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  cs_build_ok=yes break
+  cs_cv_cxx_qsqrt_ok=yes
 else
-  echo "$as_me: failed program was:" >&5
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
+( exit $ac_status )
+cs_cv_cxx_qsqrt_ok=no
 fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-    done
-
-    CXXFLAGS=$cs_cflags_save
-    LDFLAGS=$cs_lflags_save
-    LIBS=$cs_libs_save
-    ac_ext=c
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+	    CXXFLAGS="$cs_cflags_save"
+	    ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-
-    if test $cs_build_ok = yes; then
-  cs_build_cflags=`echo x$cs_cflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_build_lflags=`echo x$cs_lflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_build_libs=`echo x$cs_libs_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	cs_cv_cxx_qsqrt_ok=yes
-else
-  cs_cv_cxx_qsqrt_ok=no
-fi
-
 fi
 echo "$as_me:$LINENO: result: $cs_cv_cxx_qsqrt_ok" >&5
 echo "${ECHO_T}$cs_cv_cxx_qsqrt_ok" >&6
-else
-  cs_cv_cxx_qsqrt_ok=no
-fi
-
 else
   cs_cv_cxx_qsqrt_ok=no
 fi
@@ -19522,7 +19475,10 @@ fi
 # Check if a compiler bug discovered in gcc 2.96 (RedHat and other unstable
 # versions) and gcc 3.0.1 causes qint() to misbehave.
 # -----------------------------------------------------------------------------
-echo "$as_me:$LINENO: checking if qint() functions correctly" >&5
+
+
+
+    echo "$as_me:$LINENO: checking if qint() functions correctly" >&5
 echo $ECHO_N "checking if qint() functions correctly... $ECHO_C" >&6
 if test "${cs_cv_cxx_qint_ok+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -19533,12 +19489,9 @@ ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
-    cs_cflags_save="$CXXFLAGS"
-    if test $ac_compiler_gnu = yes; then
-  CXXFLAGS="$CXXFLAGS -O2"
-fi
-
-    if test "$cross_compiling" = yes; then
+	cs_cflags_save="$CXXFLAGS"
+	CXXFLAGS="$CXXFLAGS $cs_optimize_flags"
+	if test "$cross_compiling" = yes; then
   cs_cv_cxx_qint_ok=no
 else
   cat >conftest.$ac_ext <<_ACEOF
@@ -19549,10 +19502,10 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 static inline long double2int(double val) {
-		long* l;
-		val += 68719476736.0;
-		l = (long*)((char*)&val + 2);
-		return *l; }
+		    long* l;
+		    val += 68719476736.0;
+		    l = (long*)((char*)&val + 2);
+		    return *l; }
 int
 main ()
 {
@@ -19583,8 +19536,8 @@ cs_cv_cxx_qint_ok=no
 fi
 rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
-    CXXFLAGS="$cs_cflags_save"
-    ac_ext=c
+	CXXFLAGS="$cs_cflags_save"
+	ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
@@ -19593,7 +19546,6 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 fi
 echo "$as_me:$LINENO: result: $cs_cv_cxx_qint_ok" >&5
 echo "${ECHO_T}$cs_cv_cxx_qint_ok" >&6
-
 if test $cs_cv_cxx_qint_ok = no; then
   cs_header_text="${cs_header_text}#define CS_QINT_WORKAROUND
 "
