abort if libz is missing
git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/trunk@14468 8cc4aa7f-3514-0410-904f-f2cc9021211c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -865,106 +865,84 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --enable-cpu-specific-instructions
                           enable CPU-specific code generation (default YES);
-                          use with caution
- since code for one CPU will not
+                          use with caution since code for one CPU will not
                           work with earlier CPUs (for example,
                           Pentium-specific code will not run on an Intel 486)
   --disable-freetypetest  Do not try to compile and run
                           a test FreeType program
-  --enable-optimize       build with optimizations enabled (default YES);
-                          same as --enable-mode=optimize
-  --enable-debug          build with debugging information (default NO);
- same
+  --enable-optimize       build with optimizations enabled (default YES); same
+                          as --enable-mode=optimize
+  --enable-debug          build with debugging information (default NO); same
                           as --enable-mode=debug
-  --enable-profile        build with profiling information (default NO);
- same
+  --enable-profile        build with profiling information (default NO); same
                           as --enable-mode=profile
   --enable-mode=mode      set build mode; recognized modes are `optimize',
-                          `debug', `profile'
- (default OPTIMIZE)
+                          `debug', `profile' (default OPTIMIZE)
   --enable-plugins        create plugin modules instead of static link
                           libraries (default YES)
   --enable-extensive-memory-debugger
                           enable the extensive memory debugger which catches
-                          common memory
- management mistakes (default NO)
+                          common memory management mistakes (default NO)
   --enable-new-renderer   enable use of new renderer (_EXPERIMENTAL_!)
                           (default NO)
   --enable-makefile-cache enable caching of makefile information to speed up
-                          build process;
- (default YES)
+                          build process; (default YES)
   --enable-makefile-cache-monitor
                           auto-refresh makefile cache when source makefiles
-                          change
- (default YES); auto-refresh entails very
-                          slight performance
- penalty but is more robust
+                          change (default YES); auto-refresh entails very
+                          slight performance penalty but is more robust
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-x                use the X Window System
   --with-libXxf86vm=dir   specify location of libXxf86vm if not detected
-                          automatically; searches dir,
- dir/include, and
+                          automatically; searches dir, dir/include, and
                           dir/lib
   --with-mesa             use Mesa OpenGL library if available (default YES)
   --with-libz=dir         specify location of libz if not detected
-                          automatically; searches dir,
- dir/include, and
+                          automatically; searches dir, dir/include, and
                           dir/lib
   --with-libpng=dir       specify location of libpng if not detected
-                          automatically; searches dir,
- dir/include, and
+                          automatically; searches dir, dir/include, and
                           dir/lib
   --with-libjpeg=dir      specify location of libjpeg if not detected
-                          automatically; searches dir,
- dir/include, and
+                          automatically; searches dir, dir/include, and
                           dir/lib
   --with-libmng=dir       specify location of libmng if not detected
-                          automatically; searches dir,
- dir/include, and
+                          automatically; searches dir, dir/include, and
                           dir/lib
   --with-libmikmod=dir    specify location of libmikmod if not detected
-                          automatically; searches dir,
- dir/include, and
+                          automatically; searches dir, dir/include, and
                           dir/lib
   --with-libogg=dir       specify location of libogg if not detected
-                          automatically; searches dir,
- dir/include, and
+                          automatically; searches dir, dir/include, and
                           dir/lib
   --with-libvorbis=dir    specify location of libvorbis if not detected
-                          automatically; searches dir,
- dir/include, and
+                          automatically; searches dir, dir/include, and
                           dir/lib
   --with-libvorbisfile=dir
                           specify location of libvorbisfile if not detected
-                          automatically; searches dir,
- dir/include, and
+                          automatically; searches dir, dir/include, and
                           dir/lib
   --with-libpgserver=dir  specify location of libpgserver if not detected
-                          automatically; searches dir,
- dir/include, and
+                          automatically; searches dir, dir/include, and
                           dir/lib
   --with-lib3ds=dir       specify location of lib3ds if not detected
-                          automatically; searches dir,
- dir/include, and
+                          automatically; searches dir, dir/include, and
                           dir/lib
   --with-libode=dir       specify location of libode if not detected
-                          automatically; searches dir,
- dir/include, and
+                          automatically; searches dir, dir/include, and
                           dir/lib
   --with-ft-prefix=PREFIX
                           Prefix where FreeType is installed (optional)
   --with-ft-exec-prefix=PREFIX
                           Exec prefix where FreeType is installed (optional)
   --with-libvga=dir       specify location of libvga if not detected
-                          automatically; searches dir,
- dir/include, and
+                          automatically; searches dir, dir/include, and
                           dir/lib
   --with-libcal3d=dir     specify location of libcal3d if not detected
-                          automatically; searches dir,
- dir/include, and
+                          automatically; searches dir, dir/include, and
                           dir/lib
 
 Some influential environment variables:
@@ -2798,31 +2776,12 @@ echo $ECHO_N "checking if bison version >= 1.35... $ECHO_C" >&6
 if test "${cs_cv_prog_bison_version_ok+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-
-cs_prog_bison_is_version=
-cs_prog_bison_min_version=
-cs_prog_bison_is_suffix=
-cs_prog_bison_min_suffix=
-cs_prog_bison_is_suffix_done=
-cs_prog_bison_min_suffix_done=
-
-
-
-test -z $cs_prog_bison_is_version && cs_prog_bison_is_version=`$BISONBIN -V | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
-test -n "$cs_prog_bison_is_version" && test -z $cs_prog_bison_is_suffix_done  && { cs_prog_bison_is_suffix_done=yes ; cs_prog_bison_is_suffix= ; }
-
-
-
-
-
-test -z $cs_prog_bison_min_version && cs_prog_bison_min_version=`echo 1.35 | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
-test -n "$cs_prog_bison_min_version" && test -z $cs_prog_bison_min_suffix_done  && { cs_prog_bison_min_suffix_done=yes ; cs_prog_bison_min_suffix= ; }
-
-
-cs_prog_bison_is_ver_1=`echo ${cs_prog_bison_is_version}${cs_prog_bison_is_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1/'`
-cs_prog_bison_is_ver_2=`echo ${cs_prog_bison_is_version}${cs_prog_bison_is_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\2/'`
-cs_prog_bison_min_ver_1=`echo $cs_prog_bison_min_version${cs_prog_bison_min_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1/'`
-cs_prog_bison_min_ver_2=`echo $cs_prog_bison_min_version${cs_prog_bison_min_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\2/'`
+  cs_prog_bison_is_version=`$BISONBIN -V | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
+cs_prog_bison_min_version=`echo 1.35 | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
+cs_prog_bison_is_ver_1=`echo $cs_prog_bison_is_version | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1/'`
+cs_prog_bison_is_ver_2=`echo $cs_prog_bison_is_version | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\2/'`
+cs_prog_bison_min_ver_1=`echo $cs_prog_bison_min_version | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1/'`
+cs_prog_bison_min_ver_2=`echo $cs_prog_bison_min_version | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\2/'`
 cs_cv_prog_bison_version_ok=''
 test -z "$cs_cv_prog_bison_version_ok" && { expr "$cs_prog_bison_is_ver_1" ">=" "$cs_prog_bison_min_ver_1" >/dev/null || cs_cv_prog_bison_version_ok=no ; }
 test -z "$cs_cv_prog_bison_version_ok" && { expr "$cs_prog_bison_min_ver_1" ">=" "$cs_prog_bison_is_ver_1" >/dev/null || cs_cv_prog_bison_version_ok=yes ; }
@@ -3275,41 +3234,14 @@ echo $ECHO_N "checking if swig version >= 1.3.14... $ECHO_C" >&6
 if test "${cs_cv_prog_swig_version_ok+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-
-cs_prog_swig_is_version=
-cs_prog_swig_min_version=
-cs_prog_swig_is_suffix=
-cs_prog_swig_min_suffix=
-cs_prog_swig_is_suffix_done=
-cs_prog_swig_min_suffix_done=
-
-
-
-
-test -z $cs_prog_swig_is_version && cs_prog_swig_is_version=`$SWIGBIN -version 2>&1 | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
-test -n "$cs_prog_swig_is_version" && test -z $cs_prog_swig_is_suffix_done  && { cs_prog_swig_is_suffix_done=yes ; cs_prog_swig_is_suffix= ; }
-
-test -z $cs_prog_swig_is_version && cs_prog_swig_is_version=`$SWIGBIN -version 2>&1 | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
-test -n "$cs_prog_swig_is_version" && test -z $cs_prog_swig_is_suffix_done  && { cs_prog_swig_is_suffix_done=yes ; cs_prog_swig_is_suffix=.0 ; }
-
-
-
-
-
-
-test -z $cs_prog_swig_min_version && cs_prog_swig_min_version=`echo 1.3.14 | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
-test -n "$cs_prog_swig_min_version" && test -z $cs_prog_swig_min_suffix_done  && { cs_prog_swig_min_suffix_done=yes ; cs_prog_swig_min_suffix= ; }
-
-test -z $cs_prog_swig_min_version && cs_prog_swig_min_version=`echo 1.3.14 | sed '/[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
-test -n "$cs_prog_swig_min_version" && test -z $cs_prog_swig_min_suffix_done  && { cs_prog_swig_min_suffix_done=yes ; cs_prog_swig_min_suffix=.0 ; }
-
-
-cs_prog_swig_is_ver_1=`echo ${cs_prog_swig_is_version}${cs_prog_swig_is_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1/'`
-cs_prog_swig_is_ver_2=`echo ${cs_prog_swig_is_version}${cs_prog_swig_is_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\2/'`
-cs_prog_swig_is_ver_3=`echo ${cs_prog_swig_is_version}${cs_prog_swig_is_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\3/'`
-cs_prog_swig_min_ver_1=`echo $cs_prog_swig_min_version${cs_prog_swig_min_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1/'`
-cs_prog_swig_min_ver_2=`echo $cs_prog_swig_min_version${cs_prog_swig_min_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\2/'`
-cs_prog_swig_min_ver_3=`echo $cs_prog_swig_min_version${cs_prog_swig_min_suffix} | sed '/[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\3/'`
+  cs_prog_swig_is_version=`$SWIGBIN -version 2>&1 | sed '/[0-9][0-9]*\.[0-9][0-9]*\|\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\|\.[0-9][0-9]*\).*/\1/'`
+cs_prog_swig_min_version=`echo 1.3.14 | sed '/[0-9][0-9]*\.[0-9][0-9]*\|\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\.[0-9][0-9]*\|\.[0-9][0-9]*\).*/\1/'`
+cs_prog_swig_is_ver_1=`echo $cs_prog_swig_is_version | sed '/[0-9][0-9]*\.[0-9][0-9]*\|\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\|\.\([0-9][0-9]*\).*/\1/'`
+cs_prog_swig_is_ver_2=`echo $cs_prog_swig_is_version | sed '/[0-9][0-9]*\.[0-9][0-9]*\|\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\|\.\([0-9][0-9]*\).*/\2/'`
+cs_prog_swig_is_ver_3=`echo $cs_prog_swig_is_version | sed '/[0-9][0-9]*\.[0-9][0-9]*\|\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\|\.\([0-9][0-9]*\).*/\3/'`
+cs_prog_swig_min_ver_1=`echo $cs_prog_swig_min_version | sed '/[0-9][0-9]*\.[0-9][0-9]*\|\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\|\.\([0-9][0-9]*\).*/\1/'`
+cs_prog_swig_min_ver_2=`echo $cs_prog_swig_min_version | sed '/[0-9][0-9]*\.[0-9][0-9]*\|\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\|\.\([0-9][0-9]*\).*/\2/'`
+cs_prog_swig_min_ver_3=`echo $cs_prog_swig_min_version | sed '/[0-9][0-9]*\.[0-9][0-9]*\|\.[0-9][0-9]*/!d;s/.*\([0-9][0-9]*\)\.\([0-9][0-9]*\)\|\.\([0-9][0-9]*\).*/\3/'`
 cs_cv_prog_swig_version_ok=''
 test -z "$cs_cv_prog_swig_version_ok" && { expr "$cs_prog_swig_is_ver_1" ">=" "$cs_prog_swig_min_ver_1" >/dev/null || cs_cv_prog_swig_version_ok=no ; }
 test -z "$cs_cv_prog_swig_version_ok" && { expr "$cs_prog_swig_min_ver_1" ">=" "$cs_prog_swig_is_ver_1" >/dev/null || cs_cv_prog_swig_version_ok=yes ; }
@@ -12809,7 +12741,9 @@ fi
 fi
 
 else
-  :
+  { { echo "$as_me:$LINENO: error: zlib is essential for building CS." >&5
+echo "$as_me: error: zlib is essential for building CS." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 
@@ -21263,12 +21197,6 @@ done
 
 
 
-
-
-
-
-
-
 for ac_header in unistd.h \
     sys/types.h \
     sys/socket.h \
@@ -22559,11 +22487,9 @@ if test "${enable_mode+set}" = set; then
   enableval="$enable_mode"
   case $enableval in
 	optimize|debug|profile) cs_build_mode=$enableval ;;
-	*) { { echo "$as_me:$LINENO: error: unrecognized mode --enable-mode=$enableval;
- use
+	*) { { echo "$as_me:$LINENO: error: unrecognized mode --enable-mode=$enableval; use
     \`optimize', \`debug', or \`profile'" >&5
-echo "$as_me: error: unrecognized mode --enable-mode=$enableval;
- use
+echo "$as_me: error: unrecognized mode --enable-mode=$enableval; use
     \`optimize', \`debug', or \`profile'" >&2;}
    { (exit 1); exit 1; }; } ;;
     esac
