res merged r25656 into 1.0 (python detection).
git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/branches/release/V1.0@25657 8cc4aa7f-3514-0410-904f-f2cc9021211c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11084,13 +11084,19 @@ else
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); } | tr '\\\\' '/' | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
-	    cs_cv_pybase_lflags=''
+	    cs_cv_pybase_lflags_base=''
 	    if test -d "$cs_cv_pybase_syslib"; then
-  cs_cv_pybase_lflags="$cs_cv_pybase_lflags -L$cs_cv_pybase_syslib"
+  cs_cv_pybase_lflags_base="$cs_cv_pybase_lflags_base -L$cs_cv_pybase_syslib"
 fi
 
-	    if test -d "$cs_cv_pybase_syslib/config"; then
-  cs_cv_pybase_lflags="$cs_cv_pybase_lflags -L$cs_cv_pybase_syslib/config"
+<<<<<<< .working
+	    cs_cv_pybase_lflags_ext=''
+	    if test -d "$=======
+	    cs_cv_pybase_lflags_ext='$cs_cv_pybase_lflags_base'
+	    if test -d "$>>>>>>> .merge-right.r25656
+		cs_cv_pybase_syslib/config"; then
+  cs_cv_pybase_lflags_ext="$cs_cv_pybase_lflags_ext -L$>>>>>>> .merge-right.r25656
+		cs_cv_pybase_syslib/config"
 fi
 
 	    if test -d "$cs_cv_pybase_sysprefix/lib"; then
@@ -11158,14 +11164,22 @@ echo "${ECHO_T}$cs_cv_python_sdk" >&6
 fi
 
 	    cs_pywinlib=`echo "$cs_cv_pybase" | sed 's/\.//g'`
-	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_lflags -framework Python | sed 'y% %#%'`"
+	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_lflags_base -framework Python | sed 'y% %#%'`"
 	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_sysprefix_lflags -framework Python | sed 'y% %#%'`"
-	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_lflags -l$cs_cv_pybase | sed 'y% %#%'`"
+	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_lflags_ext -framework Python | sed 'y% %#%'`"
+
+	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_lflags_base -l$cs_cv_pybase | sed 'y% %#%'`"
 	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_sysprefix_lflags -l$cs_cv_pybase | sed 'y% %#%'`"
-	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_lflags -l$cs_pywinlib | sed 'y% %#%'`"
+	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_lflags_ext -l$cs_cv_pybase | sed 'y% %#%'`"
+
+	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_lflags_base -l$cs_pywinlib | sed 'y% %#%'`"
 	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_sysprefix_lflags -l$cs_pywinlib | sed 'y% %#%'`"
-	    cs_pyflags="$cs_pyflags `echo @@-bundle -flat_namespace -undefined suppress@$cs_cv_pybase_lflags | sed 'y% %#%'`"
+	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_lflags_ext -l$cs_pywinlib | sed 'y% %#%'`"
+
+	    cs_pyflags="$cs_pyflags `echo @@-bundle -flat_namespace -undefined suppress@$cs_cv_pybase_lflags_base | sed 'y% %#%'`"
 	    cs_pyflags="$cs_pyflags `echo @@-bundle -flat_namespace -undefined suppress@$cs_cv_pybase_sysprefix_lflags | sed 'y% %#%'`"
+	    cs_pyflags="$cs_pyflags `echo @@-bundle -flat_namespace -undefined suppress@$cs_cv_pybase_lflags_ext | sed 'y% %#%'`"
+
 	    if test "" != yes; then
   echo "$as_me:$LINENO: checking if python SDK is usable" >&5
 echo $ECHO_N "checking if python SDK is usable... $ECHO_C" >&6
@@ -11545,7 +11559,478 @@ if test "${ac_cv_path_JAVA+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   case $JAVA in
-  [\\/]* | ?:[\\/]*)
+  \\/* | ?:\\/*"; then
+  cs_cv_pybase_lflags_ext="$cs_cv_pybase_lflags_ext -L$=======
+	    cs_cv_pybase_lflags_ext='$cs_cv_pybase_lflags_base'
+	    if test -d "$>>>>>>> .merge-right.r25656
+		cs_cv_pybase_syslib/config"; then
+  cs_cv_pybase_lflags_ext="$cs_cv_pybase_lflags_ext -L$>>>>>>> .merge-right.r25656
+		cs_cv_pybase_syslib/config"
+fi
+
+	    if test -d "$cs_cv_pybase_sysprefix/lib"; then
+  cs_cv_pybase_sysprefix_lflags="$cs_cv_pybase_sysprefix_lflags -L$cs_cv_pybase_sysprefix/lib"
+fi
+
+	    if test -d "$cs_cv_pybase_sysprefix/libs"; then
+  cs_cv_pybase_sysprefix_lflags="$cs_cv_pybase_sysprefix_lflags -L$cs_cv_pybase_sysprefix/libs"
+fi
+
+
+	    cs_cv_pybase_libs=`{ (echo "$as_me:$LINENO: \$PYTHON -c \\
+		'import distutils.sysconfig; \\
+		print (distutils.sysconfig.get_config_var(\"LIBS\") or \"\")+\" \"+ \\
+		      (distutils.sysconfig.get_config_var(\"SYSLIBS\") or \"\")'") >&5
+  ($PYTHON -c \
+		'import distutils.sysconfig; \
+		print (distutils.sysconfig.get_config_var("LIBS") or "")+" "+ \
+		      (distutils.sysconfig.get_config_var("SYSLIBS") or "")') 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } | tr '\\\\' '/' | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+
+	    cs_cv_python_ext=`{ (echo "$as_me:$LINENO: \$PYTHON -c \\
+		'import distutils.sysconfig; \\
+		print (distutils.sysconfig.get_config_var(\"SO\") or \"\")'") >&5
+  ($PYTHON -c \
+		'import distutils.sysconfig; \
+		print (distutils.sysconfig.get_config_var("SO") or "")') 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }`
+
+	    if test -n "$cs_pyver" &&
+		   test -n "$cs_cv_pybase_cflags" &&
+		   test -n "$cs_cv_pybase_lflags$cs_cv_pybase_sysprefix_lflags"; then
+  cs_cv_python_sdk=yes
+else
+  cs_cv_python_sdk=no
+fi
+
+fi
+echo "$as_me:$LINENO: result: $cs_cv_python_sdk" >&5
+echo "${ECHO_T}$cs_cv_python_sdk" >&6
+
+	# Check if Python SDK is usable.  The most common library name is the
+	# basename with a few decorations (for example, libpython2.2.a),
+	# however some Windows libraries lack the decimal point (for example,
+	# libpython22.a or python22.lib), so we must check for both variations.
+	# Furthermore, MacOS/X 10.3 supplies a Python.framework, however,
+	# earlier releases did not.  Instead, Python on MacOS/X pre-10.3 uses a
+	# one-level linker namespace, which means that loadable Python modules
+	# do not link against the Python library; instead, unresolved symbols
+	# in the modules are satisfied automatically by the Python executable
+	# when the module is loaded into the executable.  For this reason,
+	# Python on MacOS/X does not even provide a Python link library.  We
+	# account for this by trying -bundle, rather than linking against the
+	# library.
+	if test $cs_cv_python_sdk = yes; then
+  cs_build_prop_val="$cs_cv_python_ext"
+    cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+    if test -n "$cs_build_prop_val"; then
+  cs_jamconfig_text="${cs_jamconfig_text}PYTHON.MODULE_EXT ?= \"$cs_build_prop_val\" ;
+"
+fi
+
+	    cs_pywinlib=`echo "$cs_cv_pybase" | sed 's/\.//g'`
+	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_lflags_base -framework Python | sed 'y% %#%'`"
+	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_sysprefix_lflags -framework Python | sed 'y% %#%'`"
+	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_lflags_ext -framework Python | sed 'y% %#%'`"
+
+	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_lflags_base -l$cs_cv_pybase | sed 'y% %#%'`"
+	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_sysprefix_lflags -l$cs_cv_pybase | sed 'y% %#%'`"
+	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_lflags_ext -l$cs_cv_pybase | sed 'y% %#%'`"
+
+	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_lflags_base -l$cs_pywinlib | sed 'y% %#%'`"
+	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_sysprefix_lflags -l$cs_pywinlib | sed 'y% %#%'`"
+	    cs_pyflags="$cs_pyflags `echo @@@$cs_cv_pybase_lflags_ext -l$cs_pywinlib | sed 'y% %#%'`"
+
+	    cs_pyflags="$cs_pyflags `echo @@-bundle -flat_namespace -undefined suppress@$cs_cv_pybase_lflags_base | sed 'y% %#%'`"
+	    cs_pyflags="$cs_pyflags `echo @@-bundle -flat_namespace -undefined suppress@$cs_cv_pybase_sysprefix_lflags | sed 'y% %#%'`"
+	    cs_pyflags="$cs_pyflags `echo @@-bundle -flat_namespace -undefined suppress@$cs_cv_pybase_lflags_ext | sed 'y% %#%'`"
+
+	    if test "" != yes; then
+  echo "$as_me:$LINENO: checking if python SDK is usable" >&5
+echo $ECHO_N "checking if python SDK is usable... $ECHO_C" >&6
+if test "${cs_cv_python+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+    cs_cflags_save="$CFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+
+    for cs_build_item in $cs_pyflags
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
+else
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CFLAGS="$cs_cflags_test $cs_cv_pybase_cflags $cs_cv_sys_pthread_cflags $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test                      $cs_cv_sys_pthread_lflags $cs_lflags_save"
+	LIBS="$cs_libs_test $cs_cv_pybase_libs   $cs_cv_sys_pthread_libs $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <Python.h>
+int
+main ()
+{
+Py_Initialize(); Py_Finalize();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cs_build_ok=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+	if test $cs_build_ok = yes; then
+  break
+fi
+
+    done
+
+
+    CFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test $cs_cv_pybase_cflags $cs_cv_sys_pthread_cflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test                      $cs_cv_sys_pthread_lflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test $cs_cv_pybase_libs   $cs_cv_sys_pthread_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_python=yes
+		cs_cv_python_cflags=$cs_build_cflags
+		cs_cv_python_lflags=$cs_build_lflags
+		cs_cv_python_libs=$cs_build_libs
+else
+  cs_cv_python=no
+fi
+
+fi
+echo "$as_me:$LINENO: result: $cs_cv_python" >&5
+echo "${ECHO_T}$cs_cv_python" >&6
+else
+  echo "$as_me:$LINENO: checking if python SDK is usable" >&5
+echo $ECHO_N "checking if python SDK is usable... $ECHO_C" >&6
+	    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+    cs_cflags_save="$CFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+
+    for cs_build_item in $cs_pyflags
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
+else
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CFLAGS="$cs_cflags_test $cs_cv_pybase_cflags $cs_cv_sys_pthread_cflags $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test                      $cs_cv_sys_pthread_lflags $cs_lflags_save"
+	LIBS="$cs_libs_test $cs_cv_pybase_libs   $cs_cv_sys_pthread_libs $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <Python.h>
+int
+main ()
+{
+Py_Initialize(); Py_Finalize();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cs_build_ok=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+	if test $cs_build_ok = yes; then
+  break
+fi
+
+    done
+
+
+    CFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test $cs_cv_pybase_cflags $cs_cv_sys_pthread_cflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test                      $cs_cv_sys_pthread_lflags | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test $cs_cv_pybase_libs   $cs_cv_sys_pthread_libs | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_python=yes
+		cs_cv_python_cflags=$cs_build_cflags
+		cs_cv_python_lflags=$cs_build_lflags
+		cs_cv_python_libs=$cs_build_libs
+else
+  cs_cv_python=no
+fi
+
+	    echo "$as_me:$LINENO: result: $cs_cv_python" >&5
+echo "${ECHO_T}$cs_cv_python" >&6
+fi
+
+    if test $cs_cv_python = yes; then
+  if test "$cs_cv_python" = yes; then
+  cs_build_prop_val="yes"
+    cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+    if test -n "$cs_build_prop_val"; then
+  cs_jamconfig_text="${cs_jamconfig_text}PYTHON.AVAILABLE ?= \"$cs_build_prop_val\" ;
+"
+fi
+
+	cs_build_prop_val="$cs_cv_python_cflags"
+    cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+    if test -n "$cs_build_prop_val"; then
+  cs_jamconfig_text="${cs_jamconfig_text}PYTHON.CFLAGS ?= \"$cs_build_prop_val\" ;
+"
+fi
+
+	cs_build_prop_val="$cs_cv_python_lflags $cs_cv_python_libs"
+    cs_build_prop_val=`echo x$cs_build_prop_val | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+    if test -n "$cs_build_prop_val"; then
+  cs_jamconfig_text="${cs_jamconfig_text}PYTHON.LFLAGS ?= \"$cs_build_prop_val\" ;
+"
+fi
+
+fi
+
+else
+  cs_cv_python_cflags=''
+	cs_cv_python_lflags=''
+	cs_cv_python_libs=''
+
+fi
+
+else
+  cs_cv_python=no
+fi
+
+else
+  cs_cv_python=no
+fi
+
+
+
+
+#------------------------------------------------------------------------------
+# Check if Java2 SDK is installed and which compiler and linker flags are
+# needed.  Also check if Ant build tool, which is commonly used to build Java
+# projects, is available.
+#------------------------------------------------------------------------------
+
+
+JAVA_HOME=`echo "x$JAVA_HOME" | tr '\\\\' '/' | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+
+if test -z "$JAVA" && test -n "$JAVACMD"; then
+  JAVA=`echo "x$JAVACMD" | tr '\\\\' '/' | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+fi
+
+
+    if test "$cs_prog_path_prepared" != yes; then
+  cs_prog_path_prepared=yes
+	PATH="$PATH$PATH_SEPARATOR/usr/local/bin$PATH_SEPARATOR/sw/bin"
+	export PATH
+fi
+
+    for ac_prog in java
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_JAVA+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $JAVA in
+  \\/* | ?:\\/*"
+fi
+
   ac_cv_path_JAVA="$JAVA" # Let the user override the test with a path.
   ;;
   *)
