Eric Sunshine made the following changes to the configure script:
-*- Worked around issue reported by Wouter with g++ 3.2 where compiler
    complained about extra -I/usr/local/include flag (something about
    order of system search path order being changed).

-*- No longer refreshes makefile cache twice if the cache already existed
    prior to run of configure (and if config.mak changed).

-*- No longer tries to be smart about locating makedep in the CS
    directory.  This caused problems because the path was not properly
    recorded and would fail if the user did not have "." in PATH.


git-svn-id: http://crystal.svn.sourceforge.net/svnroot/crystal/CS/trunk@12219 8cc4aa7f-3514-0410-904f-f2cc9021211c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3113,38 +3113,35 @@ fi
 # would like to eliminate this in the future and just use the stock version
 # rather than the specially augumented one.
 #------------------------------------------------------------------------------
-# Extract the first word of "makedep", so it can be a program name with args.
-set dummy makedep; ac_word=$2
+for ac_prog in makedep
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_MAKEDEP+set}" = set; then
+if test "${ac_cv_prog_MAKEDEP+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $MAKEDEP in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_MAKEDEP="$MAKEDEP" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-as_dummy="$PATH:."
-for as_dir in $as_dummy
+  if test -n "$MAKEDEP"; then
+  ac_cv_prog_MAKEDEP="$MAKEDEP" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
 do
   IFS=$as_save_IFS
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_MAKEDEP="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_prog_MAKEDEP="$ac_prog"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
 done
 done
 
-  ;;
-esac
 fi
-MAKEDEP=$ac_cv_path_MAKEDEP
-
+fi
+MAKEDEP=$ac_cv_prog_MAKEDEP
 if test -n "$MAKEDEP"; then
   echo "$as_me:$LINENO: result: $MAKEDEP" >&5
 echo "${ECHO_T}$MAKEDEP" >&6
@@ -3152,6 +3149,9 @@ else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
+
+  test -n "$MAKEDEP" && break
+done
 
 if test -n "$MAKEDEP"; then
   echo "$as_me:$LINENO: checking for makedep extensions" >&5
@@ -4078,6 +4078,146 @@ echo "${ECHO_T}$cs_cv_prog_cxx_enable_warnings" >&6
 "
 fi
 
+
+
+
+#------------------------------------------------------------------------------
+# Check how to make compiler treat warnings as errors.
+#------------------------------------------------------------------------------
+echo "$as_me:$LINENO: checking how to treat warnings as errors" >&5
+echo $ECHO_N "checking how to treat warnings as errors... $ECHO_C" >&6
+if test "${cs_cv_prog_cxx_enable_errors+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+    cs_cflags_save="$CXXFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+    for cs_build_item in `echo @-Werror@@ | sed 'y% %#%'`
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
+else
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CXXFLAGS="$cs_cflags_test  $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
+	LIBS="$cs_libs_test  $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cs_build_ok=yes break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+    done
+
+    CXXFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_prog_cxx_enable_errors=$cs_build_cflags
+else
+  cs_cv_prog_cxx_enable_errors=no
+fi
+
+fi
+echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_enable_errors" >&5
+echo "${ECHO_T}$cs_cv_prog_cxx_enable_errors" >&6
 
 
 
@@ -6506,6 +6646,163 @@ fi
 
 if test $cs_cv_prog_cxx_debug_gdb != no; then
   cs_makefile_text="${cs_makefile_text}LFLAGS.debug += $cs_cv_prog_cxx_debug_gdb
+"
+fi
+
+
+
+
+#------------------------------------------------------------------------------
+# Check if compiler complains about adding /usr/local/include to the header
+# search path.  If not, add this to the search path since not all compilers
+# search there by default.  Some compiler, on the other hand, complain if it is
+# already in the built-in search path, and the complaint is an annoyance.
+#------------------------------------------------------------------------------
+if test $cs_cv_prog_cxx_enable_warnings != no && \
+    test $cs_cv_prog_cxx_enable_errors != no; then
+  echo "$as_me:$LINENO: checking checking if -I/usr/local/include is usable" >&5
+echo $ECHO_N "checking checking if -I/usr/local/include is usable... $ECHO_C" >&6
+if test "${cs_cv_prog_cxx_local_include+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+    cs_cflags_save="$CXXFLAGS"
+    cs_lflags_save="$LDFLAGS"
+    cs_libs_save="$LIBS"
+    cs_build_ok=no
+
+    for cs_build_item in `echo @-I/usr/local/include \
+		$cs_cv_prog_cxx_enable_warnings \
+		$cs_cv_prog_cxx_enable_errors@@ | sed 'y% %#%'`
+    do
+
+    set filler `echo "$cs_build_item" | awk 'BEGIN { FS="@" }
+	{ for (i=1; i <= NF; ++i)
+	    { if ($i == "") print "filler"; else print $i } }'`
+    shift
+    if test $# -eq 0; then
+  cs_dummy=''
+else
+  if test "$1" = filler; then
+  cs_dummy=''
+else
+  cs_dummy=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_cflags_test=''
+else
+  if test "$1" = filler; then
+  cs_cflags_test=''
+else
+  cs_cflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_lflags_test=''
+else
+  if test "$1" = filler; then
+  cs_lflags_test=''
+else
+  cs_lflags_test=$1
+fi
+
+	shift
+fi
+if test $# -eq 0; then
+  cs_libs_test=''
+else
+  if test "$1" = filler; then
+  cs_libs_test=''
+else
+  cs_libs_test=$1
+fi
+
+	shift
+fi
+
+    cs_cflags_test=`echo $cs_cflags_test | sed 'y%#% %'`
+    cs_lflags_test=`echo $cs_lflags_test | sed 'y%#% %'`
+    cs_libs_test=`echo $cs_libs_test | sed 'y%#% %'`
+
+	CXXFLAGS="$cs_cflags_test  $cs_cflags_save"
+	LDFLAGS="$cs_lflags_test  $cs_lflags_save"
+	LIBS="$cs_libs_test  $cs_libs_save"
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cs_build_ok=yes break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+    done
+
+    CXXFLAGS=$cs_cflags_save
+    LDFLAGS=$cs_lflags_save
+    LIBS=$cs_libs_save
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    if test $cs_build_ok = yes; then
+  cs_build_cflags=`echo x$cs_cflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_lflags=`echo x$cs_lflags_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_build_libs=`echo x$cs_libs_test  | sed 's/^x//;s/   */ /g;s/^ //;s/ $//'`
+	cs_cv_prog_cxx_local_include=yes
+else
+  cs_cv_prog_cxx_local_include=no
+fi
+
+fi
+echo "$as_me:$LINENO: result: $cs_cv_prog_cxx_local_include" >&5
+echo "${ECHO_T}$cs_cv_prog_cxx_local_include" >&6
+else
+  cs_cv_prog_cxx_local_include=yes
+fi
+
+
+if test $cs_cv_prog_cxx_local_include = yes; then
+  cs_makefile_text="${cs_makefile_text}CFLAGS.SYSTEM += -I/usr/local/include
 "
 fi
 
@@ -16985,7 +17282,7 @@ echo "$as_me: config.mak is unchanged" >&6;}
 		rm -f config.mak
 		mv $tmp/tcache config.mak
 	    fi ;;
-    cache.mak ) ${MAKE} recache ;;
+    cache.mak ) rm -f cache.mak ; ${MAKE} recache ;;
   esac
 done
 _ACEOF
